= Typescript inversify

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon@wisoft.io
:Date: 2018.07.06
:Revision: 1.0
:imagesdir: ./image

Typescript inversify에 대한 세미나 내용 정리

- IDE는 WebStorm을 사용한다.
- 언어는 Typescript를 사용한다.

Byeongsoon Jang<byeongsoon@wisoft.io>

|===
|===

우선 WebStorm에서 Create New Project를 클릭하고 Empty Project를 생성한다.

----
$ npm init
// npm init을 통해 package.json 파일이 생성 된다.
----

package name, version, description, entry point, test command, git repository, keyword, author, license 등의 정보를 적어 준다.

----
$ npm i -S typescript // typescript를 npm을 통해서 install
$ ./node_modules/.bin/tsc --init // tsc를 init하면 tsconfig.json 파일이 생성된다.
----

다음은 사용할 모듈들을 다운로드 해준다.

----
$ npm i -D koa-bodyparser @types/koa-bodyparser koa-morgan @types/koa-morgan koa-router @types/koa-router inversify inversify-koa-utils reflect-metadata superagent
----

위와 같은 작업을 마치면 package.json 파일의 dependencies와 devDependencies가 다음과 같은 형식으로 되어있는 것을 확인 할 수 있다.
----
{
  "dependencies": {
    "ts-node": "^6.1.2",
    "tslint": "^5.10.0",
    "typescript": "^2.9.2"
  },
  "devDependencies": {
    "@types/chai": "^4.1.4",
    "@types/koa": "^2.0.46",
    "@types/koa-bodyparser": "^5.0.0",
    "@types/koa-morgan": "^1.0.4",
    "@types/koa-router": "^7.0.29",
    "@types/mocha": "^5.2.3",
    "@types/node": "^10.3.4",
    "chai": "^4.1.2",
    "inversify": "^4.13.0",
    "inversify-koa-utils": "^1.0.0",
    "koa": "^2.5.1",
    "koa-bodyparser": "^4.2.1",
    "koa-morgan": "^1.0.1",
    "koa-router": "^7.4.0",
    "mocha": "^5.2.0",
    "reflect-metadata": "^0.1.12",
    "superagent": "^3.8.3"
  }
}
----

다음으로는 생성된 tsconfig.json 파일을 수정할 것이다.

.기존 tsconfig.json
----
{
  "compilerOptions": {
    /* Basic Options */
    "target": "es5",
    "module": "commonjs",

    /* Strict Type-Checking Options */
    "strict": true,

    /* Additional Checks */

    /* Module Resolution Options */
    "esModuleInterop": true

    /* Source Map Options */

    /* Experimental Options */

  }
}
----

.변경 후 tsconfig.json
----
{
  "compilerOptions": {
    /* Basic Options */
    "target": "ES2017",
    "module": "commonjs",
    "lib": [
      "dom",
      "es6"
    ],
    "sourceMap": true,
     "outDir": "./build",

    /* Strict Type-Checking Options */
    "strict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": false,

    /* Additional Checks */

    /* Module Resolution Options */
    "moduleResolution": "node",
    "esModuleInterop": true,

    /* Source Map Options */

    /* Experimental Options */
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
----

나머지 옵션들은 상황과 필요에 맞게 수정해주면 된다.

다음은 package.json 파일에서 "script" 부분에 "build"를 추가해준다.

.package.json 파일 일부
----
"scripts": {
    "build": "tsc"
}
----

이제부터는 의존성 주입(DI)와 제어 역전(IoC)를 위한 예제 코드를 작성해 본다.

예제로 사용할 코드는 회원 가입, 회원 찾기, 삭제 등에 대한 account에 대한 코드이다.

첫 번째로 작성할 코드는 가입시 필요한 정보를 저장하는 account.ts이다.

.src/main/account/account.ts
[source, typescript]
----
export default class Account {
  private id: number;
  private username: string;
  private email: string;

  constructor(id: number, username: string, email: string) {
    this.id = id;
    this.username = username;
    this.email = email;
  }

  public getId(): number {
    return this.id;
  }
}
----

다른 곳에서 이 클래스를 사용할 것이기 때문에 export 해주었다.

다음으로는 데이터의 교환을 할때 사용되는 객체인 DTO(=VO )객체를 만든다.

[TIP]
====
일반적인 DTO는 로직을 갖고 있지 않는 순수한 데이터 객체이며 속성과 그 속성에 접근하기 위한 getter, setter 메소드만 가진 클래스를 말한다
====

.src/main/account/dto/account.dto.ts
[source, typescript]
----
export default interface IAccountDto {
  id: number;
  username: string;
  email: string;
}
----

DTO까지 만들고 나면 이제는 실질적인 기능을 수행하는 account.repository.ts 파일을 작성한다.

여기서는 findAll(), findById(id), register(account), remove(account_id)를 작성한다.

.src/main/account/account.repository.ts
[source, typescript]
----
import Account from './account'
import {injectable} from "inversify";

@injectable()
export default class AccountRepository {
  private repository: Array<Account> = [
    new Account(1, 'jang', 'byeongsoon@wisoft.io'),
    new Account(2, 'byeongsoon', 'qudtns1223@naver.com'),
    new Account(3, 'jangbong', 'qudtns1223@gmail.com')
  ];

  public findAll(): Array<Account> {
    return this.repository;
  }

  public async findById(id: number): Promise<Account> {
    const result: Account = await this.repository.filter((acc) => acc.getId() === id)[0];
    return result;
  }

  public register(account: Account): number {
    this.repository.push(account);
    return account.getId();
  }

  public async remove(accountId: number): Promise<number> {
    let result = 0;
    const findAccount = await this.findById(accountId);
    if (accountId === findAccount.getId()) {
      this.repository[accountId - 1] = new Account(0, '', '');
      result++;
    }
    return result;
  }
}
----

위에서는 데이터베이스에 연결하지 않고 Array에 객체를 담아서 진행했다.

다음은 위에서 작성한 repository에 대한 기능을 전달받는 account.service.ts 파일을 작성한다.

.src/main/account/account.service.ts
[source, typescript]
----
import Account from './account';
import AccountRepository from './account.repository';
import {inject, injectable} from "inversify";

@injectable()
export default class AccountService {
  private accountRepository: AccountRepository;

  constructor(@inject('AccountRepository')accountRepository: AccountRepository) {
    this.accountRepository = accountRepository;
  }

  public findAll(): Array<Account> {
    return this.accountRepository.findAll();
  }

  public findById(accountId: number):Promise<Account> {
    return this.accountRepository.findById(accountId);
  }

  public register(account: Account): number {
    return this.accountRepository.register(account);
  }

  public remove(accountId: number): Promise<number> {
    return this.accountRepository.remove(accountId);
  }
}
----

private으로 AccountRepository를 설정한 뒤에 inject()를 이용해 주입을 받는다.

이렇게 하고나면 기존에 Repository에서 담당하는 기능들을 service에서 실행할 수 있게 된다.

지금까지 기본적인 준비를 했다.

다음은 service가 가지고 있는 기능들을 http 메소드에 맞게 실행 시켜줄 수 있는 controller를 작성한다.

@controller를 이용해 path에 따른 클래스의 메소드를 실행할 수 있다.

.src/main/account/account.controller.ts
[source, typescript]
----
import 'reflect-metadata';
import Account from './account';
import AccountService from './account.service';
import IAccountDto from './dto/account.dto';
import {inject, injectable} from "inversify";
import {controller, httpDelete, httpGet, httpPost, interfaces, requestBody, requestParam} from "inversify-koa-utils";


@injectable()
@controller('/accounts')
export default class AccountController {
  private accountService: AccountService;

  constructor(@inject('AccountService')accountService: AccountService) {
    this.accountService = accountService;
  }

  @httpGet('/')
  public findAll(): Array<Account> {
    return this.accountService.findAll();
  }

  @httpGet('/:id')
  public findById(@requestParam('id')accountId: string): Promise<Account> {
    return this.accountService.findById(parseInt(accountId,10));
  }

  @httpPost('/')
  public register(@requestBody()accountDto: IAccountDto): number {
    const account: Account = new Account(accountDto.id, accountDto.username,accountDto.email);
    return this.accountService.register(account);
  }

  @httpDelete('/:id')
  public remove(@requestParam('id')accountId: string): Promise<number>{
    return this.accountService.remove(parseInt(accountId,10));
  }

}
----

지금가지 account에 대한 코드 작성을 모두 마쳤다.

다음은 테스트를 위한 App.ts 파일을 작성한다.

.src/main/App.ts
[source, typescript]
----
import {interfaces, InversifyKoaServer, TYPE} from "inversify-koa-utils";
import {Container} from "inversify";
import BodyParser from 'koa-bodyparser';
import * as Koa from 'koa';
import AccountController from "./account/account.controller";
import AccountService from "./account/account.service";
import AccountRepository from "./account/account.repository";

export default class App {
  private PORT = process.env.PORT || 3000;
  private app: Koa;
  private server: InversifyKoaServer;
  private container: Container;

  constructor(){
    this.createContainer();
    this.createServer();
  }

  private createContainer(): void {
    this.container = new Container();

    this.container.bind<interfaces.Controller>(TYPE.Controller).to(AccountController).whenTargetNamed("AccountController");
    this.container.bind<AccountService>('AccountService').to(AccountService);
    this.container.bind<AccountRepository>("AccountRepository").to(AccountRepository);
  }

  private createServer(): void {
    const environment = process.env.NODE_ENV || 'development';
    this.server = new InversifyKoaServer(this.container);

    this.server.setConfig((app) => {
      app.use(BodyParser());
    });

    this.app = this.server.build();
    this.app.listen(this.PORT,() => {
      console.log(`Listening on port: ${this.PORT}`);
    })
  }

  public static main(): App {
    return new App();
  }
}

App.main();
----

여기까지 모두 작성한 뒤에는 build 해준다.

----
$ npm run build
----

이 명령어를 마치면 build/account/*, build/App.js 파일이 생성되어 있는 것을 볼 수 있다.
