==== bitbat를 이용한 github 잔디관리

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon94@gmail.com
:Date: 2021.1.3
:Revision: 1.0
:imagesdir: ./image

새해를 기념해 github 잔디관리를 도와줄 기능을 소개한다.

{Author}<{Email}>

---

개발자라면 누구나 생각해봤을 1일 1커밋인 잔디를 관리하는 것이 아닐까싶다.

꾸준히 개발을 해오면 Contribution에 초록색 박스가 생기는데 보통 github 잔디라고 이야기한다.

1일 1커밋은 생각보다 쉽지 않은 일이다.

====
Bitbar - Put anything in your Mac OS X menu bar
====

==== Bitbar 설치하고 잔디 관리하기

먼저 bitbar를 설치한다. 맥에서 brew를 사용하고 있다면 한줄의 명령으로 설치가 가능하다.

----
brew cask install bitbar
----

설치 이후 bitbar를 실행하면 Plugin들을 설치할 디렉토리를 설정하게 된다.

설치를 완료하고 디렉토리 설정까지 마쳤다면 이제는 우리에게 필요한 플러그인 소스를 받으면 된다.

link:https://github.com/matryer/bitbar-plugins[여기]에 들어가면 다양한 플러그인들이 나오는데 기존의 방법은 bitbar 홈페이지에서 다운로드가 가능했지만 지금은 접속을하면 github 페이지로 넘어간다.

그렇기 때문에 기존 다른 개발자들이 포스팅한 내용과 조금은 다를 수 있다.

해당 github에 접속한 다음에 bitbar-plugins/Dev/GitHub/github-contribution.10m.rb 해당 위치에 들어가고 플러그인을 저장할 디렉토리에서

----
touch github-contribution.10m.rb
vi github-contribution.10m.rb
----

를 통해 ruby 코드를 옮겨준다.

필자는 여기서 ruby를 처음 사용해봐서 맥에 설치가 안되어 있었다.

----
brew install ruby
----

역시 brew를 통해서 쉽게 설치할 수 있다.

그 다음 ~/.bitbarrc 파일을 생성하고 하단의 내용을 입력해준다.

----
# ~/.bitbarrc
[github_contribution]
username = ByeongSoon (여기는 본인의 github id)
max_contributions = 10
----

설정이 끝났다면 bitbar의 Preferences - Refresh All을 클릭하면 된다.

하지만 오류가 난다!! 그 이유는 우선 .rb 파일을 내가 만들었기 때문에 실행파일이 아닌 일반 텍스트 파일이었다.

----
chmod 744 github-contribution.10m.rb
----

위 명령어를 통해서 실행권한을 주고 다시 Refresh All을 해주니 상단에 bitbar github 플러그인 메뉴바가 실행되었다.

하지만 문제는 역시나 계속해서 발생.... Contribution이 오늘 날짜가 아닌 2021-12-31 기준으로 나오는 것이다.

이후 해결책은 해결하는데로 추가할예정이다..
