= 1강 - 스프링이란?

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon@wisoft.io
:Date: 2018.07.26
:Revision: 1.0

인프런 '신입 프로그래머를 위한 자바 스프링(Spring) 프레임워크 강좌’

* 프레임워크
* 스프링(Spring)
* 설치

Byeongsoon Jang<byeongsoon@wisoft.io>

|===
|===

스프링은 국내에서 표준 프레임워크 -> 대부분 프로젝트 스프링 프레임워크 사용

==== 1-1. 프레임워크

프레임워크란, 특정한 목적에 맞게 프로그래밍을 쉽게 하기 위한 약속.

프로그램을 개발하다보면 무수히 많은 프레임워크를 접할 것이다.

가장 최근에 등장하고 가장 많이 접할 수 있는게 안드로이드 프레임워크.

.프레임워크 예시
====
사용자는 손님이고, 식당을 갔다. 오늘은 화요일.

식당에는 요일에 특정메뉴를 저렴하게 판매하는 요일메뉴가 있다.

화요일의 요일 메뉴는 제육볶음.

손님은 직원에게 '제육볶음 하나 주세요.'라고 말하면,
직원은 카운터, 주방장에게 '요일 하나 있어요~' 라고 말한다.

주방장은 '제육볶음'을 만든다.
====

손님이 말한 것을 그대로 전달한 것이 아니라 약속된 요일 메뉴가 있기 때문에 제육볶음이라고 명시하지 않고 요일 메뉴라고 표현하였다.

이렇게 약속된 형태의 일련의 과정들을 '프레임워크'라고 한다.

==== 1-2. 스프링(Spring)

자바(JAVA)언어를 기반으로, 다양한 어플리케이션을 제작하기 위한 약속된 프로그래밍 틀.

예전엔 EJB의 경우 고가의 장비(WAS 등의)가 필요 되어지고, 개발환경 및 설정 그리고 테스트 환경에 많은 애로사항들이 존재했다.
하지만 스프링의 경우 톰캣을 이용할 수 있으며, EJB에 비해서 코드의 경량화 그리고 개발 중에 테스트가 쉽다는 점이 특징이다.

-> EJB보다 스프링이 진입 장벽이 낮다.

* 스프링의 국내에서 자바개발자들에게 표준프레임워크가 되었다.
** 스프링의 기본을 정확히 학습한다면, 다양한 어플리케이션을 쉽고 빨리 개발할 수 있을 것이다.

* 프레임워크 안에는 무수히 많은 기능들이 포함되어 있으므로 처음 공부할 때에는 모든걸 완벽히 익히려는 생각은 빨리 지칠 수 있다.
** 학습을 처음에는 가볍게, 학습한 것을 토대로 여러가지 프로젝트를 수행해보자.
** 무한반복의 학습을 통해서 내 것으로 만들자.

* 스프링은 계속해서 업데이트(버전업) 되고 있으며, 업데이트 되는 내용에 대한 꾸준한 학습이 필요하다.

====
물론 스프링 학습 이전에는 JAVA, JSP&Servlet에 대한 선행학습이 반듯이 필요하며, 그 외에 html, javascript, jquery, css 등의 스크립트 언어도 기본적인 학습이 필요하다.

특히, JSP&Servlet에서는 MVC Model2는 확실하게 알고 있는게 좋다.
====

==== 1-3 설치

* JDK 설치 - 필자는 OpenJDK 8, 10 버전을 사용.
** Windows 운영체제는 JAVA 환경변수 설정 해야한다. link:https://github.com/ByeongSoon/TIL/blob/master/Java/java_8_Download_Tutorial.adoc[링크]참조

* IDE(개발툴) 이클립스 설치(다운로드)
** link:http://www.eclipse.org[이클립스] 접속
** 필자는 JetBrain사의 IntelliJ 사용

* 톰캣 다운로드 link://http://tomcat.apache.org[링크]접속
** Tomcat 7.0을 사용

* IDE와 Tomcat 연동
