= 4강 DI(Dependency Injection) (2)

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon@wisoft.io
:Date: 2018.08.01
:Revision: 1.0

인프런 '신입 프로그래머를 위한 자바 스프링(Spring) 프레임워크 강좌’

* 스프링 프로퍼티 설정
* 스프링 컨테이너의 이해

Byeongsoon Jang<byeongsoon@wisoft.io>

|===
|===

==== 강의 전 복습

==== 4-1 스프링 프로퍼티 설정

스프링 프로퍼티 설정에 대한 기본적인 사항들을 학습한다.

기본적이라고 하지만, 가장 많이 쓰이고 꼭 알고 있어야 한다.

* <bean>태그 아래 <property> 아래의 <value>는 객체의 필드에 대한 기본 값을 입력할 수 있다.
** 이 <value>는 객체의 필드 타입이 String, double, int에 상관없이 입력해도 된다.
*** ArrayList<>인 타입은 <list>태그로 명시해주면 된다.
** 타입은 중요하지 않다. 어차피 박싱처리 해준다.

* 다른 객체(타입)을 참조할 수 있다.
** <ref bean="">을 이용한다.

* 이렇게 <property> 태그를 사용할 수 있는 이유는 setter()를 갖고 있기 때문이다.
** 꼭 setter()를 만들고 나서 사용하길 바란다.

.applicationCTX.xml
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

    <bean id="bmiCalculator" class="wisoft.io.BMICalculator">
        <property name="lowWeight">
            <value>18.5</value>
        </property>
        <property name="normal">
            <value>23</value>
        </property>
        <property name="obesity">
            <value>25</value>
        </property>
        <property name="overWeight">
            <value>30</value>
        </property>
    </bean>

    <bean id="myInfo" class="wisoft.io.MyInfo">
        <property name="name">
            <value>홍길동</value>
        </property>
        <property name="height">
            <value>185</value>
        </property>
        <property name="weight">
            <value>84</value>
        </property>
        <property name="hobbys">
            <list>
                <value>수영</value>
                <value>요리</value>
                <value>독서</value>
            </list>
        </property>
        <property name="bmiCalculator">
            <ref bean="bmiCalculator" />
        </property>
    </bean>

</beans>
----

.BMICalculator.java
[source, java]
----
package wisoft.io;

public class BMICalculator {

  private double lowWeight;
  private double normal;
  private double overWeight;
  private double obesity;

  public void bmiCalculation(double weight, double height) {

    double h = height * 0.01;
    double result = weight / (h*h);

    System.out.println("BMI 지수 : " + (int)result);

    if (result > obesity) {
      System.out.println("비만 입니다.");
    } else if (result > overWeight) {
      System.out.println("과체중 입니다.");
    } else if (result > normal) {
      System.out.println("정상 입니다.");
    } else {
      System.out.println("저체중 입니다.");
    }
  }

  public void setLowWeight(double lowWeight) {
    this.lowWeight = lowWeight;
  }

  public void setNormal(double normal) {
    this.normal = normal;
  }

  public void setOverWeight(double overWeight) {
    this.overWeight = overWeight;
  }

  public void setObesity(double obesity) {
    this.obesity = obesity;
  }
}
----

.MyInfo.java
[source, java]
----
public class MyInfo {
  private String name;
  private double height;
  private double weight;
  private ArrayList<String> hobbys;
  private BMICalculator bmiCalculator;

  public BMICalculator getBmiCalculator() {
    return bmiCalculator;
  }

  public void setName(String name) {
    this.name = name;
  }

  public void setHeight(double height) {
    this.height = height;
  }

  public void setWeight(double weight) {
    this.weight = weight;
  }

  public void setHobbys(ArrayList<String> hobbys) {
    this.hobbys = hobbys;
  }

  public void setBmiCalculator(BMICalculator bmiCalculator) {
    this.bmiCalculator = bmiCalculator;
  }
}
----

.MainClass.java
[source, java]
----
public class MainClass {

  public static void main(String[] args){
    String configuration = "classpath:applicationCTX.xml";
    AbstractApplicationContext ctx = new GenericXmlApplicationContext(configuration);
    MyInfo myInfo = ctx.getBean("myInfo", MyInfo.class);

    myInfo.getInfo();

    ctx.close();
  }

}
----

* <bean> 태그의 id는 사용할 id값.

* <property> 태그의 name은 객체의 필드명.
** <property>는 setter()를 이용해서 값을 넣어주기 때문에 name에 넣었던 값의 앞글자만 대문자로 바꾸고 앞에 set을 붙인 메서드를 찾는다.
** <value>태그는 타입에 상관없이 입력해도 자동으로 박싱되어 들어간다.

* ctx를 이용해서 할당받은 자원은 다 사용하고 나면 해제해 줘야한다.
** 'ctx.close()'

==== 4-2 스프링 컨테이너의 이해

[source, java]
----
String configLocation = "classpath:applicationCTX.xml";
AbstractApplicationContext ctx = new GenericXmlApplicationContext(configLocation);// 스프링 컨테이너 생성
MyInfo myInfo = ctx.getBean("myInfo", MyInfo.class);// 스프링 컨테이너에서 컴포넌트 가져옮
myInfo.getInfo();
ctx.close();
----

* AbstractApplicationContext를 상속하는 여러개의 클래스가 있다.
** 상속받은 클래스 중에서 우리는 GenericXmlApplicationContext 클래스를 사용한다.

* getBean()은 Bean 객체를 뽑아오는 것이다.
* 객체를 생성하고 조립하는 것은 스프링 컨테이너(IOC 컨테이너)가 하고있다.
