= http와 https란

:icons: font
:Author: Byeongsoon Jang
:Email: qudtns1223@gmail.com
:Date: 2020.4.8.
:Revision: 1.0
:imagesdir: ./image

보안관제 업무를 교육받으면서 가장 기초적인 질문인
http와 https가 무엇인지 알고있냐는 질문에 대략적으로만 답변을하여 다시한번 개념을 정리해보고자 한다.

Byeongsoon Jang<qudtns1223@gmail.com>

---

=== 1. http란

우리가 평소에 사용하는 인터넷 사이트는 모두 접속 가능한 URL을 가지고 있다.

URL이란 Uniform Resource Locator로 네트워크 상에서 위치를 알려주기 위한 규약이다.

URL에 접속하는 경우 해당 URL에 맞는 프로토콜을 알아야 한다.
FTP 프로토콜인 경우 FTP 클라이언트를 사용하고, HTTP 프로토콜은 웹 브라우저를 사용한다.

HTTP(HyperText Transfer Protocol)은 웹 브라우저 사이에 문서를 전송하기 위한 통신 규약이다.

HTTP 서버는 기본 포트인 80포트를 사용하며 클라이언트가 TCP 80포트를 사용해 연결하면 서버는 요청에 응답하며 정보를 전송한다.

=== 2. https란

https는 http에 S(Secure Socket)을 추가한 것이다.
기본적인 사용 목적이나 짜여진 틀은 거의 동일하지만, 데이터를 주고 받는 과정에 보안을 추가한 것이다.

가장 단순하게 말하면 https를 사용하면 서버와 클라이언트가 데이터를 주고받는 통신 내용이 암호화되어서 된다는 것이다.

https는 웹 서버에 접속하는 사용자 모두에게 동일한 암호를 제공하는 것이 아니라 각각 다른 암호를 제공해야 한다.

====
기본적으로 클라이언트와 사이트 시스템(서버) 간의 통신에 사용되는 HTTP Port는 80이고, HTTPS 포트는 443이다.
====

=== 3.추후 학습내용

구글링 결과 https를 적용한 웹 페이지를 만들기 위해선 SSL이라는 기술을 사용하는 것 같다.

Spring boot의 SSL 적용하기란 키워드가 제일 많이 검색되는 것으로 보아 해당 기능을 쉽게 적용할 수 있도록 제공하는 라이브러리가 있는 것 같다.

보안까지 생각해가며 코딩을 해나가야 하므로 Spring boot 학습 시 유심히 학습해야 한다.
