= 모놀리식 아키텍처와 마이크로서비스 아키텍처

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon@wisoft.io
:Date: 2018.06.24
:Revision: 1.0
:imagesdir: ./image

Node.js 마이크로서비스 코딩 공작소 - 정대천 지음, 길벗

위 책을 학습하고 두 아키텍처의 개념과 차이점을 남김.

Byeongsoon Jang<byeongsoon@wisoft.io>

|===
|===

==== 모놀리식 아키텍처

- 모놀리식 아키텍처란 널리 활용하는 전통적인 아키텍처로 하나의 애플리케이션 안에 모든 컴포넌트를 포함하는 구조.
구조가 단순해 개발과 배포가 간단하다는 장점이 있다.

모놀리식 아키텍처를 이해하면 마이크로서비스 아키텍처를 더 쉽게 이해할 수 있다.

==== 모놀리식 아키텍처의 한계

모놀리식 아키텍처는 개발과 배포가 쉽다는 장점이 있지만, 일체형 시스템이라서 여러 한계가 있다.

- 분산 처리가 비효율적이다
** 모놀리식 아키텍처는 모든 기능을 프로세스 하나 또는 코드 베이스로 개발하기 떄문에 기능별로 분산 처리를 할 수 없다.
항상 같이 분산해야 한다.

- 코드를 관리하기 어렵다
** 코드 구조가 하나이기에 새로운 코드를 추가하려면 전체 코드를 이해해야 하고 코드를 추가할수록 구조가 복잡해진다.

- 새로운 기술을 적용하기 어렵다
** 특정 기능에 새로운 기술을 적용하고 싶어도 기능별로 코드가 독립적이지 않아 적용하기 쉽지 않다.

==== 분산 아키텍처의 필요성

- 코드 수정에 부담이 없어야 하고, 새로운 기능을 추가할 때는 기존 코드에 영향을 주지 않아야 한다.
- 필요한 기능만 분산 처리할 수 있어야 하고, 다른 기능에 결함이 발생해도 영향을 받지 않아야 한다.
- 기능별로 최적화돤 기술을 적용할 수 있어야 하고, 각기 다른 기술로 작성한 코드가 유기적으로 동작해야 한다.

==== 마이크로서비스란

커다란 모놀리식 아키텍처를 단독으로 실행 가능한 다수의 모듈로 분해한 아키텍처를 마이크로서비스 아키텍처라고 한다.
이때 실행 가능한 하나의 모듈을 마이크로 서비스라고 한다.

- 마이크로 서비스의 특징
** 마이크로서비스는 하나의 독립적인 프로세스 하나를 의미한다.
** 개발과 배포에 상호 독립적이다.
** 기술 독립성을 가진다.
** 독립적인 데이터 저장소를 가질 수 있다.
** 각 마이크로서비스는 각자 가진 네트워크 기능으로 통신할 수 있다.

모놀리식 아키텍처의 문제 대부분은 모든 기능을 프로세스 하나로 개발하는 데서 발생한다.
관리하기 적당한 작은 단위로 기능을 분리하면 앞에서 언급한 문재점인 비효율적인 분산 처리와 코드의 복잡성을 해결할 수 있고, 기능별 최적화된 언어 및 프레임워크도 사용할 수 있다.

==== 마이크로서비스 아키텍처의 단점

- 공유 자원 접근이 어렵다
** 예를 들어, 구매 관리 마이크로서비스가 회원 관리 마이크로서비스의 데이터를 참조해야 할 경우 모놀리식 아키텍처라면 프로세스가 같기 때문에 어렵기 않게 구매 관리 로직에서 회원 관리 로직으로 접근할 수 있다.

- 배포와 실행이 복잡해진다
** 모놀리식 아키텍처에서는 프로세스 하나만 실행해도 서비스가 가능했지만, 마이크로 서비스는 복잡한 실행 과정을 거쳐야만 정상적인 서비스가 가능하다.

- 분산 시스템을 구현하기 어렵다
** 마이크로 서비스에는 독립적인 프로세스들을 유기적으로 동작할 수 있게 하는 분산 네트워크 시스템이 필요하다.
매우 중요한 시스템이지만 네트워크 레벨에서 다양한 상황별로 처리해야 하므로 구현하기 어려울 수 있다.
