= 코틀린 시작하기

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon@wisoft.io
:Date: 2018.02.26
:Revision: 1.0
:imagesdir: ./img

코틀린 프로그래밍 - 스티븐 사무엘, 스테판 보큐리우 지음

1장 코틀린 시작하기

Byeongsoon Jang<byeongsoon@wisoft.io>

|===
|===

=== 개요

Kotlin은 2011년 Jetbrain사가 공개한 JVM에서 동작하는 프로그래밍 언어이다.
JVM에서 동작하는 코틀린은 자바와 100%의 호환성을 보인다.

IntelliJ IDEA를 이용해 코틀린을 학습한다. IntelliJ 15버전 부터는 코틀린을 위한 별도의 패키지 설치가 필요없다.

구글에서 안드로이드 공식언어로 지정하기도 했다.

Kotlin은 기존 Java 기반 기술과의 완벽한 호환성을 유지하면서 간결하게 코드를 작성할 수 있는
서버 측 응용 프로그램 개발에 매우 적합하다.

OS X를 사용하고 homebrew가 설치되어 있다는 가정하에 다음과 같은 명령어로 코틀린을 다운받는다.

[source]
----
& brew install kotlin
----

=== Hello, World!

첫 번째 코틀린 프로그램을 작성할 수 있게 되었다.

콘솔에 Hello, World!를 출력하는 코드를 작성해보자.

우선 IntelliJ에서 new project를 누르고 Java 모듈에서 Kotlin을 선택한다.

그리고 src에 오른쪽 마우스를 가져가 클릭한 뒤에 New -> Kotlin File/Class를 클릭한다.

.HelloWorld.kt
[source, kotlin]
----
fun main(args: Array<string>){
  println("Hello, World!")
}
----

==== 커맨드라인에서 코틀린 코드를 컴파일하고 실행하기

커맨드라인에서 컴파일러를 호출해 JAR 어셈블리를 만들게한다.

----
& kotlinc HelloWorld.kt -include-runtime -d HelloWorld.jar
----

이렇게하면 커맨드라인에서 다음의 명령어를 입력하는 것으로 프로그램을 실행할 준비가 됐다.

----
& java -jar HelloWrold.jar
----

결과는 다음과 같다.

----
Hello, World!
----

이 방법 말고도 IntelliJ에서 run하면 결과는 같게나온다.

=== REPL

최근에 대부분의 언어는 대화형 쉘을 제공하며 코틀린도 예외는 아니다.
재사용하지 않는 코드를 빠르게 작성하고자 한다면 REPL은 쓰기 좋은 도구이다.

IntelliJ에서 Tool -> Kotlin -> Kotlin REPL을 클릭하면 아래 콘솔창에 코드를
간단하게 작성할 수 있는 창이 나타난다.

=== 프로젝트 생성없이 Kotlin 코드를 간단히 테스트하기

Kotlin의 코드를 실행하기위해 반드시 프로젝트를 생성해야 하는 것은 아니다.
Kotlin에서는 간단한 예제 프로젝트를 제공하고, Kotlin 코드들을 실행시킬 수 있는 웹 페이지를 제공한다.

link:https://try.kotlinlang.org/#/Examples/Hello,%20world!/Simplest%20version/Simplest%20version.kt[Try Kotlin]
이 곳을 통해서 IDEA가 없더라도 웹에서 간단하게 코드를 작성해서 실행시켜 볼 수 있다.

==== 요약

1장에선 코틀린을 빌드하고 실행하는데 필요한 도구와 개발 환경을 구축하는 방법을 학습했다.

2장부터는 개발에 실질적으로 필요한 기본 구조 문법을 배운다고한다.
