= 코틀린 기본기 (2/2)

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon@wisoft.io
:Date: 2018.03.20
:Revision: 1.0

코틀린 프로그래밍 - 스티븐 사무엘, 스테판 보큐리우 지음

2장 코틀린 기본기

Byeongsoon Jang<byeongsoon@wisoft.io>

|===
|===

==== 임포트

클래스, 객체, 인터페이스와 함수를 선언한 패키지 외부에서 이를 사용하기 위해서는 필요한 클래스, 객체 인터페이스
또는 함수를 임포트해야만 한다.

----
import com.packt.myproject.Foo
----

* 와일드 카드 임포트

만약 같은 패키지에서 다수를 임포트해야하는 상황이라면 임포트를 각각 개별적으로 명시하는 것을 피하고자 * 연산자를 사용해
한 번에 패키지 전체를 임포트할 수 있다.
----
import com.packt.myproject.*
----

* 임포트명 변경

만약 각기 다른 패키지에서 각각 같은 이름을 사용한다면 이름에 별칭을 지어주기 위해 as 키워드를 사용할 수 있다.
이는 java.io.path와 org.apache.hadoop.fs.path처럼 여러 라이브러리에서 공통된 이름을 사용하는 경우 특히 유용하다.

[source, Kotlin]
----
import com.packt.myproject.Foo
import com.packt.otherproject.Foo as Foo2

fun doubleFoo() {
  val foo1 = Foo()
  val foo2 = Foo2()
}
----

==== 문자열 템플릿

자바 개발자는 표현식과 문자열 리터럴을 혼합하기 위해 문자열 합치기 기능을 사용하는 데 익숙할 것이다.

[source, java]
----
val name = "Byeongsoon"
val concat = "Hello " + name
----

문자열 템플릿은 패턴 치환이나 문자열 연속이 필요하지 않으면서도 손쉽고 효과적인 방법으로 문자열 안에 값이나
변수, 심지어 표현식도 끼워 넣는다.

요즘에는 많은 언어에서 이러한 기능을 지원하고 있으며, 코틀린 설계자 또한 코틀리에 이를 추가하기로 했다.

사용법은 매우 단순핟. 값이나 변수에 접두사로 달러($) 기호를 추가함으로써 간단하게 추가할 수 있다.

[source, java]
----
val name = "ByeongSoon"
val str = "hello $name"
----

임의의 표현식 같은 경우에는 접두사로 달러($)를 추가하고 괄호 {}로 식을 감싸는 방법으로 추가할 수 있다.

[source, java]
----
val name = "ByeongSoon"
val str = "hello $name. Your name has ${name.length} characters"
----

==== 범위

범위는 시작하는 값과 끝나는 값 사이의 간ㅂ격으로 정의된다. 비교가 가능한 타입이기만 하면 범위를 생성하는데 사용될 수 있으며,
범위는 .. 연산자를 사용해 생성할 수 있다.

[source, Kotlin]
----
val aToz = "a".."z"
val oneToNine = 1..9
----

범위를 한번 생성하고 나면 주어진 값이 범위에 포함되는지 검사하기 위해 in 연산자를 사용할 수 있게 된다.
이것이 왜 타입을 비교할 수 있어야만 하는지에 대한 이유다.

값이 범위에 포함되기 위해서는 시작되는 값보다 크거나 같아야하고,
끝나는 값보다 작거나 같아야한다.

[source, java]
----
val aToz = "a".."z"
val isTrue = "c" in aToz
val oneToNine = 1..9
val isFalse = 11 in oneToNine
----

그뿐 아니라 .. 연산자로 처리할 수 없는 범위를 생성하기 위한 라이브러리 함수도 있는데, 예를 들면 downTo()는
숫자를 하나씩 내리는 순으로 범위를 생성하고 rangeTo()는 숫자를 하나씩 올리는 순으로 범위를 생성할 것이다.

두 함수 모두 숫자 타입에 확장함수(extension function)형태로 정의 되어 있다.

[source, java]
----
val countingDown = 100.downTo(0)
val rangeTo = 10.rangeTo(20)
----

범위를 생성하고 나면 새로운 범위를 반환하는 방법으로 범위를 변경할 수 있다. step() 함수를 사용하며 범위에 있는
연속적인 항의 델타 값을 변경할 수 있다.

[source, java]
----
val oneToFifty = 1..50
val oddNumbers = oneToFifty.step(2)
----

- step() 함수에 음수 값을 사용해 숫자가 감소하는 범위를 만들 수는 없다.

reversed() 함수를 사용하면 범위를 반전시킬 수 있다. 이름에서 유추할 수 있듯이 reversed() 함수는
시작하는 값과 끝나는 값이 서로 바뀐 새로운 범위를 반환하며, 단계 값은 감소하는 값이 된다.

[source, java]
----
val countingDownEvenNumber = (2..100).step(2).reversed()
----

==== 루프

코틀린은 여러 언어에서 볼 수 있는 일반적인 루프 구조인 while 루프와 for 두 가지를 지원한다.
코틀린에서 사용하는 while 루프 문법은 대부분의 C 스타일 언어와 정확하게 일치하기 때문에 개발자들에게 친숙할 것이다.

[source, java]
----
while(true) {
  println("This will print out for a long time!")
}
----

코틀린의 for 루프는 이터레이터(iterator)라는 이름의 함수나 확장함수를 정의한 객체를 반복하는 데 사용된다.
모든 컬렉션은 이 함수를 제공한다.

[source, java]
----
val list = listOf(1,2,3,4)
for (k in list) {
  println(k)
}

val set = setOf{1, 2, 3, 4}
for (k in set) {
  println(k)
}
----

for 루프 문법에서 in 키워드를 사용하고 있음을 확인하자. in 연산자는 항상 for 루프와 함께 사용된다.
연속적인 범위는 컬렉션을 지원하는 것뿐만 아니라 인라인 또는 바깥에서 정의하는 것도 직접 지원한다.

[IMPORTANT]
====
컴파일러는 범위를 특별한 방법으로 처리하며, JVM에서 직접 지원하는 인덱스 기반의 for 루프로 컴파일한다.
이로 인해 이터레이터 객체를 생성함으로써 발생하는 성능상의 불이익을 피할 수 있다.
====

[TIP]
====
for 루프를 사용하는 또 다른 방법

[source, java]
----
val array = arrayOf(1,2,3,4)
array.forEach {
  println(it)
}

array.for Each {
  k -> println(k)
}
----
====

==== 예외처리

예외를 처리하는 방식은 자바의 예외 처리 방식과 거의 같지만 한 가지 중요한 차이점이 있는데, 코틀린에서 모든 예외는
확인되지 않은 예외(unchecked exception)라는 점이다.

확인된 예외(checked exception)은 반드시 메소드 시그니처 부분에 선언하거나 메소드 내부에서 다뤄야 한다.
대표적인 예로 IOException이 있는데, 여러 File 함수에서 IOException을 발생시킨다. 그러므로 IO라이브러리 곳곳에서
IOException을 선언한다.

예외를 처리할 때는 자바와 마찬가지로 try, catch, finally 블록을 사용한다. 안전하게 처리하고자 하는 코드는 try 블록으로 감싸고, catch 블록은 추가하지
않을 수도 있지만, 추가하면 다른 예외를 처리할 수 있으며, finally 블록은 예외 발생 여부에 관계 없이 항상 실행된다.

다음 예제는 IOException을 발생시킬 수 있는 경우로 내부에서 잠재적인 예외를 처리하는 코드이다.

입력 스트림은 읽기 성공여부에 관계없이 닫혀야만 하므로 finally 블록으로 close() 함수를 감싸준다.

[source, java]
----
fun readFile(path: Path): Unit {
  val input = Files.newInputStream(path)
  try{
    var byte = input.read()
    while(byte != -1) {
      println(byte)
      byte = input.read()
    }
  } catch (e: IOException) {
    println("Error reading from file. Error was ${e.message}")
  } finally {
    input.close()
  }
}
----

==== 클래스 인스턴스화하기

[TIP]
====
인스턴스란 기존 자바에서 클래스를 new 키워드를 사용해 만들어진 객체를 인스턴스라 부른다.
====

많은 언어에서는 new 키워드를 사용하고 뒤이어 생성하고자 하는 클래스명이 따라오는 문법을 사용한다.
new 키워드는 컴파일러에 새로운 인스턴스를 초기화 하려면 생성자 함수가 실행돼야 한다고 알려준다.

코틀린은 생성자 함수가 클래스명을 사용함으로써 생성자 함수 호출을 일반 함수를 호출하는 것과 똑같이 처리한다.
이로인해 코틀린에서 new 키워드를 완전히 빼버리게 해주었다.
인자는 평소와 같이 전달된다.

[source, java]
----
val file = File("/etc/nginx/nginx.conf")
val data = BigDecimal(100)
----

==== 참조 동등성과 구조 동등성

객체 지향 프로그래밍을 지원하는 언어에는 두 가지의 동등성 개념이 존재한다.
첫 번째는 두 개의 각기 다른 참조가 메모리상에서 정확하게 같은 인스턴스를 가리키고 있는 경우다.
두 번째는 메모리상에서 두 객체는 각기 다른 인스턴스이지만 같은 값을 갖고 있는 경우다.

첫 번째를 *참조 동등성(referential equality)* 이라 부른다. 두 참조가 같은 인스턴스를 가리키는지를 확인하기 위해서는 === 연산자(삼중 일치)나
같지 않은 경우를 확인하는 !== 연산자를 사용한다.

[source, java]
----
val a = File("mobydick.doc")
val b = File("mobydick.doc")
val sameRef = a === b
----

두 번째는 *구조 동등성(structural equality)* 이라 부른다. 두 객체가 같은 값을 가졌는지 확인하기 위해서는
== 연산자 또는 같지 않음을 확인하는 != 연산자를 사용한다.
이러한 함수 호출은 equals() 함수를 사용하는 것으로 전환된다.

[source, Kotlin]
----
val a = File("mobydick.doc")
val b = File("mobydick.doc")
val sameRef = a == b
----

[IMPORTANT]
====
자바에서 == 연산자가 사용되는 방법과는 다르다는 사실을 명심해야 한다. 자바에서 == 연산자는 참조 동등성을 위한 것이며,
이는 일반적으로 피해야 하는 사항이다.

== 연산자는 널 값에 대해 안전하다. 즉, 컴파일러가 널 체크를 해줄 것이기 때문에 널 인스턴스를 검사하더라도 걱정할 필요가 없다는 뜻이다.
====

==== this 표현식

클랙스나 함수 내부에서 이를 둘러싼 인스턴스를 참조하고 싶을 때가 있다. 예를 들어, 한 인스턴스는 자기 자신을 인자로 전달해
메소드를 작동시키고자 한다. 이와같은 경우에 this 키워드를 사용한다.

[source,Kotlin]
----
class Person(name: String) {
  fun printMe() = println(this)
}
----

코틀린 용어에서 this 키워드로 참조되고자 하는 참조를 현재 수신자(current receiver)라 부른다.
왜냐하면 이 인스턴스가 함수 호출을 받은 인스턴스이기 때문이다.

클래스의 멤버에서 this는 클래스 인스턴스를 참조한다. 확장 함수에서 this는 확장 함수가 적용된 인스턴스를 참조한다.

- 중첩된 스코프에서 바깥 인스턴스를 참조하고 싶은 경우가 있을 것이다. 이를 위해서는 this 사용 권한을 얻어야만 하며,
레이블을 사용해 이를 얻을 수 있다.

여기서 사용하는 레이블은 일반적으로 바깥에 위치한 클래스명이지만 함수나 클로저를 위한 더욱 복잡한 규칙도 있으며, 이는 5장에서 다룬다.

[source, Kotlin]
----
class Building(val address: String) {
  inner class Reception(telephone: String) {
    fun printAddress() = println(this@Building.address)
  }
}
----

print 함수는 바깥 인스턴스인 Building에 접근하기 위한 권한을 얻어야만 한다는 점에 주목하자. printAddress() 함수 내부에 있는 this는
가장 가까이에 갖고 있는 클래스를 참조할 것이며, 이 경우에는 Reception 클래스를 참조하게 된다. inner 키워드는 3장에서 다룬다.

==== 가시성 제어자

일반적으로 모든 함수나 클래스가 퍼블릭 API의 일부분으로 설계되지는 않는다.
그러므로 몇몇 코드의 일부분을 내부 코드로 지정해 클래스나 패키지 바깥에서 접근하지 못하게 하는것이 바람직하다.
이를 명시하기 위해 사용되는 키워드를 가시성 제어자(visibility modifiers)라 부른다.

가시성 제어자는 *public, internal, protected, private* 이렇게 네 가지가 있다.
만약 제어자가 없다면 기본 값이 사용되며, 기본 값은 public이다. public은 이를 사용하고자 하는 코드에서 모두 볼 수 있음을 의미한다.

* private

private로 정의한 최상위 함수, 클래스 또는 인터페이스는 오직 같은 파일에서만 접근할 수 있다.

클래스, 인터페이스 또는 객체 내부에 있는 private 함수나 프로퍼티는 오직 같은 클래스나 인터페이스 또는 객체의 다른 멤버로만 접근할 수 있다.

[source, Kotlin]
----
class Person {
  private fun age(): Int = 25
} // 여기서 age() 함수는 Person 클래스 내부에 있는 다른 함수를 사용해야만 실행할 수 있다.
----

* protected

최상위 함수, 클래스, 인터페이스 그리고 객체는 protected로 선언할 수 없다.

클래스나 인터페이스 내부에서 protected로 선언한 함수나 프로퍼티는 해당 클래스 또는 인터페이스 뿐만 아니라 서브클래스 멤버까지만 접근할 수 있다.

* internal

internal은 모듈 개념을 다룬다. 모듈은 메이븐(Maven)이나 그레이들(Gradle)모듈 또는 인텔리제이 모듈로 정의된다.
internal로 정의한 코드는 같은 모듈에 있는 다른 클래스나 함수에서 접근할 수 있다.
사실상 internal은 전체에서 public처럼 동작하기 보다는 모듈에서 public처럼 동작한다.

[source, Kotlin]
----
internal class Person {
  fun age(): Int = 25
}
----

==== 표현식으로서의 흐름 제어

표현식은 값을 평가하는 구문이다. 다음 표현식은 true를 평가한다.

[source, java]
----
"hello".startWith("h")
----

반면에 구문은 결과 값을 반환하지 않는다. 아래는 변수에 값을 대입하는 구문이지만
자기 자신에 대해 어떠한 것도 평가하지 않는다.

[source, Kotlin]
----
val a = 1
----

자바에서 if ~ else, try ~ catch 같은 일반적인 흐름 제어 블록은 구문이다.

이러한 구문은 값을 평가하지 않으며 이는 자바에서는 일반적이기 때문에 이러한 구문을 사용할 때는 변수에 결과 값을
대입하기 위해 블록 밖에서 변수를 초기화 해줘야한다.

.자바에서의 경우
[source, java]
----
public boolean isZero(int x) {
  boolean isZero;
  if (x == 0)
    isZero = true;
  else
    isZero = false;
  return isZero;
}
----

* 코틀린에서 if ~ else, try ~ catch 흐름 제어 블록은 표현식이다. 이는 결과를 값에 직접 대입할 수 있으며,
함수로부터 반환할 수도 있으며 다름 함수에 인자로 전달할 수도 있다.

이 기능은 보일러플레이트 코드를 줄여주고 코드를 더욱 읽기 쉽게 해주며, 값이 변경 가능한 변수의 사용을 피하게 해준다.
if문 밖에서 변수를 선언하고 각 분기 내부에서 초기화하는 일반적인 사용 방법을 완전히 피할 수 있게 해준다.

[source, java]
----
val date = Date()
val today = if (date.year == 2018) true else false

fun isZero(x: Int): Boolean {
  return if (x == 0) true else false
}
----

이와 비슷하게 try ~ catch 블록에서도 사용할 수 있으며, 다음과 같다.

[source, java]
----
val success = try {
  readFile()
  true
} catch (e: IOException) {
  false
}
----

위 예제에서 success 변수는 성공적으로 마쳤다면 true를 그렇지 않을 경우에는 false를 가진다.

표현식이 꼭 한 줄일 필요는 없다. 표현식은 블록이 될 수도 있으며, 마지막 줄은 반드시 표현식이여 한다.

[IMPORTANT]
====
if를 표현식으로 사용할 때는 else 절을 반드시 포함해야한다. 그렇지 않으면 컴파일러는 if가 true를 평가하지 못했을 때
무엇을 해야 할지 알지 못할 것이다. 만약 else 절을 포함하지 않는다면 컴파일러는 컴파일 단계에서 에러를 표시할 것이다.
====

==== 널 문법

코틀린은 널 값을 지정할 수 있는 변수는 ?와 함께 선언할 것을 요구한다.

[source, java]
----
var str: String? = null
----

이 외에도 코틀린은 NullPointerException(NPE)에 맞서 대항하는 데 도움이 되는 다양한 기능을 갖고 있으먀,
널과 안정성에 대해서는 7장에서 자세하게 학습한다.

타입 확인과 형변환도 있다. 만약 어떠한 인스턴스 참조가 일반적인 타입 A로 선언되어 있으면, 좀 더 구체적인 타입 B가 있는 지를 확인하고
싶을 수 있으며, 코틀린에서는 이러한 경우를 위해 is 연산자를 제공한다. is연산자는 자바에 있는 instanceof 연산자와 같다.

[source, java]
----
fun isString(any: Any): Boolean {
  return if(any is String) true else false
}
----

* 똑똑한 형변환

타입을 확인하고 나면 해당 변수를 B의 인스턴스로 참조하고 싶을 텐데, 그러기 위해서는 해당 참조를 반드시 형변환해야만 한다.
자바에서는 이를 명시적으로 수행해야 하며, 이로 인해 중복이 발생한다.

[source, java]
----
public void printStringLength(Object obj) {
  if(obj instanceof String) {
    String str = (String) obj;
    System.out.println(str.length());
  }
}
----

코틀린 컴팡일러는 더 영리해서 사용자를 대신해 타입을 확인했음을 기억해 암시적으로 참조를 더욱 구체적인 타입으로 형변환할 것이다.
이를 똑똑한 형변환 이라고 한다.

[source, java]
----
fun printStringLength(any: Any) {
  if(any is String) {
    println(any.length)
  }
}
----

컴팡일러는 변수가 정말로 문자열 인스턴스라고 한다면 코드 블록 내부에 진입할 수 있음을 알고 있기 때문에, 사용자를 위해 형변환을 수행하고 문자열
인스턴스에 정의된 메소드에 접근을 허용한다.

[TIP]
====
똑똑한 형변환에서 사용할 수 있는 변수는 변수를 검사한 시점부터 변수를 사용하는 시점 동안 값이 변하지 않음을 컴파일러가
보장할 수 있는 변수로 제한된다.

이는 변경이 되는 var 필드와 로컬 변수는 똑똑한 형변환에 사용할 수 없음을 의미한다.
====

심지어 똑똑한 형변환은 왼쪽에서 타입을 검사하는 경우, 지연 연산되는 불리언 연산자의 오른쪽에서 동작하기도 한다.

[source, java]
----
fun isEmptyString(any: Any) {
  return any is String && any.length == 0
}
----

컴파일러는 && 표현식에서는 왼쪽 값이 true가 나오지 않는 이상 오른쪽이 연산되지 않을 것임을 알고 있기 때문에,
변수는 문자열이 틀림없을 것이다. 그러므로 컴파일러는 사용자를 대신해 똑똑한 형변환을 수행해 오른쪽에서 length 프로퍼티에 접근을 허용한다.

|| 표현식에서는 왼쪽에서 참조가 특정 타입이 아닌지를 확인할 수 있다.

[source, java]
----
fun isNotStringOrEmpty(any: Any) {
  return any !is String || any.length == 0
}
----

* 명시적 형변환

어떠한 참조를 타입으로 형변호나하는데 이를 명시적으로 하기 위해서는 as 연산자를 이용한다.
자바와 마찬가지로, 형변환을 정상적으로 수행할 수 없다면 이 연산자 역시 ClassCastException을 발생시킬 것이다.

[source, java]
----
fun length(any: Any): Int {
  val string = any as String
  return string.length
}
----

타입이 널 값이 가능하도록 정의되어 있지 않기 때문에 널 값으로 형변환할 수는 없다.
널 값이 가능한 값으로 형변환하기 위해서는 그저 필요한 타입을 널 값이 가능한 타입으로 선언하기만 하면 된다.

[source, java]
----
val string: String? = any as String
----

[TIP]
====
형변환에 실패했을 경우 널 값을 대신 전달받고자 할 경우에는 안전한 형변환 연산자인 as?를 사용할 수 있다.
이 연산자는 타긴 타입이 호환이 되는 타입인 경우에는 형변환된 값을 반환할 것이며,
그렇지 않은 경우에는 널 값을 반환할 것이다.
====

==== when 표현식

C나 C++, java를 포함한 여러 언어에서는 고전적인 switch 문을 지원해왔지만 다소 제한적이었다.
그와 동시에 패턴 매칭(pattern matching) 같은 함수형 프로그래밍 개념이 점점 주류로 부상하고 있다.

코틀린은 이 둘을 혼합해, switch 문을 대신하는 강력한 when이라는 표현식을 제공한다.

when에는 두 가지 형식이 있다. 첫 번째는 인자 값이 있는 것, 두 번째는 인자 값이 없는 것이다.

* 인자가 있는 when(값)

when의 가장 간단한 예쩨는 각기 다른 상수와 비교해 매치하는 것으로, 자바 같은 언어에서 있는 switch 문의 일반적인 사용법과 유사하다.

[source, java]
----
fun whatNumber(x: Int) {
  when(x) {
    0 -> println("x is zero")
    1 -> println("x is 1")
    else -> println("x is neither 0 nor 1")
  }
}
----

when에서는 하나도 빠뜨리는 것이 없어야 하기 때문에 컴파일러는 마지막 분기가 else가 되도록 강제한다는 점에 주목하자.

if ~ else, try ~ catch와 마찬 가지로 when도 표현식으로 사용할 수 있다.

분기 코드가 같은 경우에는 상수를 함께 묶을 수도 있다. 이를 위해서는 상수를 분리하기 위해 단순히 콤마를 사용하면 된다.

[source, java]
----
fun isZeroOrOne(x: Int): Boolean {
  return when (x) {
    0,1 -> true
    else -> false
  }
}
----

다음의 코드들은 다양한 when(값)의 사용법을 알려준다.

[source, java]
----
fun isAbs(x: Int): Boolean {
  return when(x) {
    Math.abs(x) -> true
    else -> false
  }
}

fun isSingleDigit(x: Int): Boolean {
  return when(x) {
    in -9..9 -> true
    else -> false
  }
}

fun isDieNumber(x: Int): Boolean {
  return when(x) {
    in listOf(1,2,3,4,5,6) -> true
    else -> false
  }
}

fun startsWithFoo(any: Any): Boolean {
  return when(any) {
    is String -> any.startWith("Foo")
    else -> false
  }
}
----

* 인자가 없는 when

when의 두 번째 형태는 인자 없이 사용되며, 이는 if ~ else 절을 대체하게 된다.
이러한 형태는 때로는 더 깔끔한 코드를 생산할 수 있게 하는데 특히 많은 조건을 비교하는 경우가 이에 해당된다.
다음 예제는 같은 코드를 작성하는 두 가지 방법을 보여준다.

[source, java]
----
fun whenWithoutArgs(x: Int, y: Int) {
  if(x < y){
    println("x is less than y")
  } else if (x > y) {
    println("is greater than y")
  } else {
    println(x must equal y)
  }
}

fun whenWithoutArgs(x: Int, y: Int) {
  when {
    x < y -> println("x is less than y")
    x > y -> println("is greater than y")
    else -> println("x must equal y")
  }
}
----

==== 함수 반환

다음과 같은 상항에서 보면 forEach가 돌면서 stop을 만나면 return 하라고 되어있지만
여기서의 return은 가장 가까이에서 닫히는 부분까지만의 return이다.

다음 예제에서는 stop을 만나면 함수가 끝나는 것이 아니라 stop부분 만을 빼고 출력한다.

또한 return으로 반환을 할 때 레이블을 통해서 표시를 해줘야 한다. 레이블은 @로 끝나는 단순한 문자열이다.
레이블을 사용하지 않았다면 암시적 레이블을 사용한다.

[source, java]
----
fun printUntilStop() { // 명시적 레이블
  val list = listOf("a","b","stop","c")
  list.forEach stop@{
    if( it=="stop") return@stop
    else println(it)
  }
}

fun printUntilStop() { // 암시적 레이블
  val list = listOf("a","b","stop","c")
  list.forEach{
    if( it=="stop") return@forEach
    else println(it)
  }
}
----

.출력결과
----
a
b
c
----

==== 타입 체계

코틀린에서는 최상위 타입을 Any라고 부른다. 이는 자바에서 오브젝트 타입과 유사하다.
