= 코틀린 기본기 (1/2)

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon@wisoft.io
:Date: 2018.03.13
:Revision: 1.0

코틀린 프로그래밍 - 스티븐 사무엘, 스테판 보큐리우 지음

2장 코틀린 기본기

Byeongsoon Jang<byeongsoon@wisoft.io>

|===
|===

=== val과 var

코틀린에서는 변수를 선언하기 위한 키워드가 두 가지 있다.

var는 변경 가능한 변수를 선언하는 키워드로 변수에 값을 재지정하면 다른 값으로 변경될 수 있다.
이는 자바에서 변수를 선언하는 방식과 같아.

[source, java]
----
var name = "Byeongsoon Jang"
----

다음과 같이 선언과 동시에 초기화를 할 수도 있고,

[source, java]
----
var name: String
name = "Byeongsoon Jang"
----

초기화를 나중에 할 수도 있다.

위의 코드를 보면 알 수 있듯이 변수의 자료형에 대한 정보를 변수명 뒤에 표시하고 있다.

read only 변수를 선언하기 위해서는 val 키워드를 사용한다. 이는 자바에서 final 변수를 선언하는 것과 같다.

[IMPORTANT]
====
val은 나중에 변경할 수 없으므로 생성할때 반드시 초기화를 해줘야만한다.
====

[source, java]
----
val name = "Kotlin"
----

=== 타입 추론

앞선 코드에서 변수를 초기화할 때 변수 타입이 포함되어 있지 않은 것을 보았다.
이는 변수를 선언하는 과정에서 변수 타입이 반드시 동반돼야 하는 자바와는 다르다.

[TIP]
====
코틀린은 강타입 언어입에도 불구하고, 항상 타입을 명시적으로 선언할 필요가 없다.
====

컴파일러는 표현식에 포함된 정보로 해당 타입을 찾으려고 시도한다. 단순한 val은 컴파일러에게는
쉬운 사례라고 할 수 있는데, 오른쪽 값을 확인하면 타입이 명확해지기 때문이다.

이러한 메커니즘을 *타입추론(type inference)* 라 부른다.

타입 추론은 함수에 있는 표현식으로 반환 값을 추론할 수 있는 한 줄짜리 함수에도 사용할 수 있다.

[source, java]
----
fun plusOne(x: Int) = x + 1
----

때로는 :을 사용해 명시적으로 선언하는 것이 도움이 된다.

[source, java]
----
val explicitType: Number = 12.3
----

=== 기본 타입

자바와 코틀린의 간의 큰 차이점 중 하나는 코틀린에서는 모든 것이 객체라는 점이다. 자바에서는 객체와는 다르게 다루는 특별한
*원시 타입(primitive type)* 이 있다는 사실을 이미 알고 있다.

원시 타입은 *재네릭 타입(generic type)* 으로 사용될 수 없으며, 메소드나 함수 호출을 지원하지도  않고, 널 값을 할당할 수도 없다.

이러한 기본 타입의 예로는 boolean 타입이 있다.

[TIP]
====
자바는 원시 타입을 객체로 감싸는 방안을 제공하기 위해 래퍼(wrapper) 객체를 도입했으며, 이러한
방식으로 java.lang.Boolean은 boolean을 래핑해 차이점을 완하했다.

코틀린은 원시 타입을 모두 객체로 승격시킴으로써 언어에서 래퍼 객체의 필요성을 전부 제거했다.
====

- 숫자

내장된 숫자 타입은 다음과 같다.

|===

^|타입 ^|길이

|Long |64
|Int |32
|Short | 16
|Byte |8
|Double |64
|Float |32

|===

숫자 리터럴을 생성하기 위해서는 다음 형식 중 하나를 사용한다.

[TIP]
====
리터럴(Literal)이란?

리터럴은 데이터 그 자체를 뜻 한다.

변수에 넣는 변하지 않는 데이터를 의미하는 것이다.
====

[source, java]
----
val int = 123
val long = 123456L
val double = 12.34
val float = 12.34F
val hexadecimal = 0xAB
val binary = 0b01010101
----

long 값은 접미사로 *L* 을 요구하고, float는 접미사로 *F* 를 요구함을 알 수 있다.

double은 부동소수점 수 체계의 기본 값으로 사용되며 int는 정수 체계의 기본 값으로 사용된다.

hexadecimal과 binary는 각각 접두사로 0x와 0b를 사용한다.

코틀린은 자동으로 숫자를 확장하지 않기 때문에 반드시 명시적으로 변환해줘야 한다.
각 숫자는 다른 숫자 타입으로 전환할 수 있는 함수를 갖고 있다.

[source,java]
----
val int = 123
val long = int.toLong()

val float = 12.34F
val double = float.toDouble()
----

타입 간에 변환을 위한 함수 전체는 toByte(), toShort(), toInt(),
toLong(), toFloat(), toDouble(), toChar() 가 있다.

코틀린은 일반적인 비트 연산자인 왼쪽 비트 이동, 오른쪽 비트 이동, 부호가 없는 오른쪽 비트 이동,
논리곱, 논리합, 배타적 논리합을 지원한다.

[TIP]
====
자바와는 달리 이러한 연산자는 내장 연산자가 아니라 이름이 있는 함수다. 그러나 여전히 연산자처럼 실행할 수 있다.
====

[source, java]
----
val leftShift = 1 shl 2
val rightShift = 1 shr 2
val unsignedRightShift = 1 ushr 2

val and = 1 and 0x00001111
val or = 1 or 0x00001111
val xor = 1 xor 0x00001111
val inv = 1.inv()           // 역은 단항 연산자이기 때문에 숫자에 점 연사자를 사용해 호출
----

- 불리언

불리언은 부정, 논리곱, 논리합 연산자를 지원한다. 논리곱과 논리합은 왼쪽에서 조건을 만족한다면 오른쪽은
평가되지 않을 것이다. (short-circuit 이라고 한다.)

[source, java]
----
val x = 1
val y = 2
val z = 2

val isTrue = x < y && x < z
val alsoTrue = x == y || y == z
----

- 문자

char는 단일 문자를 나타낸다. 문자 리터럴은 'A' 또는 'Z'처럼 단일 따옴표를 사용한다. 또한 char는
\t, \b, \n, \r, ', ", \\, \$같은 이스케이프를 지원한다.

[TIP]
====
이스케이프란 값을 에러 없이 전달하기 위해 제어 문자자로 인식될 수 있는 특정 문자 왼쪽에 역슬래시를 붙이거나 URI 등으로 인코딩하여
제어 문자가 아닌 일반 문자로 인식시켜 에러 또는 에러를 이용한 부정행위를 방지하는 것을 말한다.
====

모든 유니코드 문자는 유니코드 숫자를 사용해 표현할 수 있는데, 예를 들면 \u1234와 같은 방식으로 표현할 수 있다.

char 타입은 자바에서처럼 숫자로 다뤄지지 않는다는 점을 기억하자.

[source, java]
----
val char = 'A'
----

- 문자열

문자열은 자바와 마찬가지로 불변이다. 문자열 리터럴은 이중 따옴표나 삼중 따옴표를 사용해 생성된다.
이중 따옴표를 사용하면 이케이프된 문자열을 생성한다. 이스케이프된 문자열에서 개행과 같은 특수문자는
반드시 이스케이프돼야 한다.

삼중 따옴표는 원시 문자열을 생성한다. 원시 문자열에서는 이스케이프가 필요하지 않으며, 모든 문자를 포함할 수 있다.

즉, 이스케이프도 표현가능하다.

[source, java]
----
val string = "string with \n new line"

var rawString = """raw string is super useful
      |for strings that span
      |many lines""".trimMargin() // """ 에서 Enter 누르면 자동으로 trimMargin이 붙음
----

결과, 이스케이프 문자 없이도 엔터를 칠 수 있다.

----
raw string is super useful
for strings that span
many lines
----

=== 배열

코틀린에서는 라이브러리 함수인 arrayOf()를 사용해 배열을 생성힐 수 있다.

[source, java]
----
var array = arrayOf(1,2,3)
----

다른 방법으로는 초기 크기와 각 요소를 생성하는 데 함수를 이용해 배열을 생성할 수 있다.

[source, java]
----
var funtionArray = Array(10,{k -> k * k})
// 0, 1, 4, 9, ..., 81

// 배열 출력은
funtionArray.forEach{
  println(it)
}
for (a in funtionArray){
  println(a)
}

----

코틀린에서는 자바와는 다르게 언어 차원에서 배열을 특별하게 다루지 않으며, 배열은 일반적인 컬렉션 클래스일 뿐이다.
배열의 인스턴스는 이터레이터 함수와 get 함수, set 함수, size 함수를 제공한다.

또한 get 함수와 set 함수는 다른 C 스타일 언어에서와 마찬가지로 괄호 문법을 지원한다.

[source, java]
----
val element1 = array[0]
val element2 = array[1]
array[2] = 5
----

코틀린에서는 ByteArray, CharArray, ShortArray, IntArray, LongArray, BooleanArray, FloatArray, DoubleArray를 제공한다.

=== 주석

코틀린에서 사용하는 주석은 자바나 자바스크립트, C 같은 언어에서 사용하는 주석과 같다.

[source, java]
----
// 라인 주석

/*
블록 주석
여러 줄을 포함할 수 있다.
*/
----

=== 패키지

패키지 네임스페이스 단위로 코드를 나눌 수 있게 해준다. 모든 파일은 패키지를 선언하는 것으로 시작하게 될 것이다.

[source, ruby]
----
package com.packt.myproject
class Foo
fun bar(): String = "bar"
----
