= 널 안정성

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon@wisoft.io
:Date: 2018.04.02
:Revision: 1.0

==== 목차

- 널을 허용하는 타입과 널을 허용하지 않는 타입
- 널에 안전한 연산자

|===
|===

==== 널을 허용하는 타입

코틀린의 타입 시스템은 널을 허용하는 타입(nullable type)과 널을 허용하지 않는 타입(non-nullable type)
간의 차이를 구분할 수 있다.
예를 들어 다음 코드는 컴파일 되지 않을 것이다.

[source, java]
----
val name: String = null // 컴파일 안됨
----

var에 널을 할당하는 것 또한 컴파일되지 않을 것이다.

[source, java]
----
var name: String = "byeongsoon"
name = null // 컴파일 안됨
----

코틀린 컴파일러에게 변수가 널을 가질 수 있도록 허용하리란 사실을 알리기 위해서는 타입에 접미사로 ?를 추가해야 한다.

[source, java]
----
val name: String? = null
val name: String? = "byeongsoon"
name = null
----

위의 코드는 모두 컴파일이 된다.

이와 마찬가지로 ?를 함수 매개변수 등에 사용함으로써 함수에서 널을 허용하는 타입과 널으 허용하지 않는 타입을 반환할 수 있다.

[source, java]
----
fun name1(): String = ...
fun name2(): String? = ...
----

name1 함수는 널 참조를 반환할 수 없다. name2 함수는 널 참조를 반환하거나 반환하지 않을 수도 있다.
만약 name1의 결과가 사용되는 코드를 작성했다면, 널 포인터 익셉션이 발생하지 않는다는 사실이 보장된다.

==== 똑똑한 형변환

똑똑한 형변환은 코틀린에 있는 기능으로 컴파일러가 if 표현식에 있는 조건을 추적한다. 변수가 널이 아님을 미리 확인하기만 하면 컴파일러는
마치 널을 허용하지 않는 타입으로 선언된 변수에 접근하는 것과 마찬가지 방식으로 변수에 접근하는 것을 허용한다.

[source, java]
----
fun getName(): String? = ...
val name = getName()
if( name != null) {
  print(name.length)
}
----

위 예제에서는 if표현식 내부에서 name 변수에 있는 length 함수를 호출하고 있음을 주목한다.
이것은 컴파일러가 name 참조가 널이 아닌 값이 아니면 블록 안으로 들어갈 수 없음을 확인했기 때문이다.

==== 안전한 널 접근

똑똑한 형변환은 매우 훌륭한 기능이며 널을 처리할 때 분기 처리를 하는 데 있어 가독성이 좋은 방안이다.
그러나 연쇄적인 연산자가 있고 각 단계에서 널을 생산할지도 모르는 경우, 코드의 가독성은 급격하게 나빠진다.

[source, Kotlin]
----
class Person(name String, val address: Address?)
class Address(name: String, postcode: String, val city: City?)
class City(name: String, val country: Country?)
class Country(val name: String)

fun getCountryName(person: Person?): String {
  var conutryName: String? = null
  if(person != null {
    val address = person.address
    if(address != null) {
      val city = address.city
      if(city != null) {
        val country = city.country
        if(country != null) {
          conutryName = contry.name
        }
      }
    }
  }

  return conutryName
}
----

요구되는 if-not-null 검사가 중첩되는 단계를 보면  가독성이 굉장히 떨어지고
더 많은 중첩 단계가 요구 될수도 있다.

코틀린은 똑똑한 형변환의 대안으로 안전한 널 접근 연산자(safe null access operator)를
사용한다.
이 연산자는 함수화 프러퍼티를 위한 일반적인 점 문법과 유사하면서 ?를 사용한다.

위의 코드는 다음과 같이 다시 작성될 수 있다.

[source, java]
----
fun getCountryName(person: Person?): String? {
  return person?.address?.city?.country?.name
}
----

차이점은 매우 분명하다. 이 함수를 위해 생성된 바이트 코드를 본다면 컴파일러가 실제로
널 검사를 추가했다는 사실을 확인할 수 있다.

==== 강제 연산자

널을 허용하지 않는 타입에 널을 러용하는 타입을 강제하고자 하는 경우가 있다. 널을 혀용하지 않는 값만
받는 함수의 변수를 사용해야 하는 경우에 유용하다. !!연산자를 사용한다.

[source, java]
----
val nullableName: String? = "george"
val name: String = nullableName!!
----

위의 예제에서 name은 널을 허용하지 않는 타입으로 선언됐고 변환을 수행하기 위해 !!가 사용됐음을 확인할 수 있다.
널을 허용하는 타입을 반환하는 모든 표현식에 이처럼 작성할 수 있다.

==== 엘비스 연산자

널을 허용하는 타입이 있을 때의 가장 일반적인 시나리오 중 하나는 값이 널이 아닌 경우에는 값을 사용하고,
그렇지 않은 경우에는 기본 값을 사용하는 것이다. 예를 들어, 자바에서는 보통 다음과 같은 코드를 작성한다.

[source, java]
----
String postcode = null;
if(address == null){
  postcode = "No Postcode";
} else {
  if(address.getPostcode()==null) {
    postcode = "No Postcode";
  } else {
    postcode = address.getPostcode();
  }
}
----

코틀린에서 이에 대한 대체자로 제공하는 것을 흔히 엘비스 연산자(Elvis operator)라고 하며,
?: 로 표기한다.

이 연산자의 사용법은 자바의 if문에 있는 삼항식과 매우 유사하다.

중위 연산자는 널을 허용하는 표현식과 널을 허용하는 표현식이 실제로 널인 경우 사용하게 되는 표현식 사이에 위치할 수 있다.

[source, java]
----
val nullableName: String? = ...
val name: String = nullableName ?: "default_name"
----

오른쪽은 표현식이기 떄문에 when 표현식이나 함수 호출처럼 값을 평가할 수 있기만 하면 어떤 것이든 위치할 수 있다.

또 다른 일반적인 방법은 기본 값을 반환하는 엘비스 연산자를 사용하기 전에 널을 허용하는 표현식을 연쇄해 안전한 널 접근 연산자와 함께 사용하는 것이다.

[source, java]
----
val nullableAddress: Address? = null
val postcode: String = nullableAddress?.postcode ?: "default_name"
----

==== 안전한 형변환

코틀린 기본기에서 변수를 형변환하는 as 연산자를 배웠다.
만약 타입을 안전하게 형변환하고자 하거나 형변환에 실패했을 때 널로 지정하고 싶은 경우에는 안전한 형변환 연산자인 as?를 사용할 수 있다.

이 예제에서는 String이라는 것을 알고 있으나 Any로 선언됐기 때문에 컴파일러는 String으로 인지하지 못하는 매개 변수에 대해 형변환을 해본다.

[source, java]
----
val location: Any = "London"
val safeString: String? = location as? String
val safeInt: Int? = location as? Int
----

결과는 safeString은 London이 출력되지만 safeInt는 null이 출력되는 것을 볼 수 있다.

==== 널이 가능한 컬렉션

널이 허용가능한 컬렉션에서 널을 허용하지 않는 컬렉션으로 값을 전달해야 한다면 filterNotNul() 함수를 이용해서
널 값을 제거하고 널을 허용하지 않는 컬렉션으로 값을 전달할 수 있다.

[source, java]
----
val nullableList: List<Int?> = listOf(1, 2, null, 4)
val intList: List<Int> = nullableList.filterNotNul()
----

위와 같이 해주면 nullableList에 세 번째 인덱스에 존재하는 null 값만을 제외하고
{1, 2, 4}의 값이 들어간다.
