= 8장. 인터페이스

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon94@gmail.com
:Date: 2020.09.03
:Revision: 1.0
:imagesdir: ./image


책 '이것이 자바다 - 신용권'를 학습하면서 기억해두면 좋은점을 기록한다.

여러번 보면서 놓쳤던 부분들을 체크하며, 기본에 충실한다.

{Author}<{Email}>

---

==== 인터페이스의 역할

자바에서 인터페이스는 객체의 사용 방법을 정의한 타입이라고 말할 수 있다.

인터페이스는 객체의 교환성을 높여주기 때문에 다형성을 구현하는 매우 중요한 역할을 한다.

[TIP]
====
자바 8의 람다식은 함수적 인터페이스의 구현 객체를 생성한다.
====

==== 인터페이스 선언

인터페이스 선언은 interface 키우드를 사용한다.

[source, java]
----
[ public ] interface 인터페이스명 {
  // 상수
  타입 상수명 = 값;

  // 추상 메소드
  타입 메소드명(매개변수,...);

  //디폴트 메소드
  default 타입 메소드명(매개변수, ...) {
    ...
  }

  // 정적 메소드
  static 타입 메소드명(매개변수, ...) {
    ...
  }
}
----

인터페이스는 상수와 메소드만을 멤버로 가진다.

자바 8부터 추가된것이 디폴트 메소드와 정적 메소드이다.

* 상수 필드(Constant Field)
** 인터페이스는 데이털르 저장할 수 있는 필드를 선언할 수 없다.
** 상수를 선언할 때에는 반드시 초기값을 대입해야 한다.

* 추상 메소드(Abstract Method)
** 호출할 때 언떤 매개값이 필요하고, 리턴 낭비이 무엇인지만 알려준다.
** 실행부는 구현 클래스에 작성한다.

* 디폴트 메소드(Default Method)
** 인터페이스에 선언되지만 구현 객체가 가지고 있는 인스턴스 메소드이다.

* 정적 메소드(Static Method)
** 디폴트 메소드와 달리 객체가 없어도 인터페이스만으로 호출이 가능하다.

상수는 선언할 때 public static final로 선언하는데 인터페이스에 선언된 필드는 모두 이 상수의 특성을 갖기 때문에 public, static, final을 생략하더라도 자동적으로 컴파일 과정에서 붙게 된다.

[TIP]
====
상수명은 대문자로 작성하되, 서로 다른 단어로 구성되어 있을 경우에는 언더바로 연결하는 것이 관례이다.

[source,java]
----
public interface Control {
  public int MAX_VOLUME = 10;
  public int MIN_VOLUME = 0;
}
----
====

인터페이스의 멤버 중 대표적인 추상 메소드는 실행 블록이 없이 리턴 타입, 메소드명, 매개 변수만 기술한다.

인터페이스에 선언된 추상 메소드는 모두 public abstract 특성을 갖기 때문에 생략해도 자동적으로 컴파일 과정에서 붙게 된다.

[source,java]
----
public void setVolume(int volume);
----

디폴트 메소드는 default 키워드가 맨앞에 위치하고, 작성 방법은 클래스의 메소드와 같다. public 특성을 갖기 때문에 생략해도 컴파일 과정에서 붙게 된다.

정적 메소드는 인터페이스로 바로 호출이 가능하다.

==== 인터페이스 구현

인터페이스에 정의한 추상 메소드의 실행 가능한 실체 메소드를 가진 객체를 구현(implement) 객체라고 하고, 구현 객체를 생성하는 클래스를 구현 클래스라고 한다.

.interface 구현 클래스
[source, java]
----
public class ClassName implements InterfaceName {
  // 인터페이스에 선언된 추상 메소드의 실체 메소드
}
----

구현 클래스는 클래스 이름 뒤에 implements 키워드를 추가하고 인터페이스명을 명시해야 한다.

구현 클래스에서 추상 메소드의 실체 메소드를 작성할 때 주의할 점은 인터페이스의 모든 메소드는 접근제한자가 public이기 때문에 public보다 더 낮은 접근 제한으로 작성할 수 없다.

[IMPORTANT]
====
만약 인터페이스에 선언된 추상 메소드에 대응하는 실체 메소드를 구현 클래스에 작성하지 않으면 구현 클래스는 자동적으로 추상 클래스가 된다.

-> 구현 클래스에서 추상 메소드의 내용을 반드시 작성하거나 구현 클래스를 선언할 때 abstract 키워드를 추가해 추상 클래스로 선언한다.
====

===== 익명 구현 객체

익명이라고 함은 말 그대로 이름이 없는 구현 객체를 만드는 것이다.

이름이 없다는 것은 따로 구현 클래스를 만들지 않고 구현 객체를 생성자 중괄호를 이용해 구현한다.

작성 시 주의할 점은 익명 구현 객체는 하나의 실행문이므로 반드시 끝에 세미콜론(;)을 붙여줘야 한다.

.익명 구현 객체
[source, java]
----
인터페이스 변수명 = new 인터페이스() {
  // 인터페이스에 선언된 추상 메소드의 실체 구현부
};
----

new 연산자 뒤에 우리는 지금까지 클래스 이름을 붙여서 생성자를 호출했었는데 여기서는 인터페이스 이름을 사용한다.

여기서 중괄호에는 인터페이스에 선언된 모든 추상 메소드의 실체 메소드를 작성하여야 한다. 클래스를 선언하는 것이 아니기 때문에 추상 메소드를 다 이용하지 않으면 추상 클래스가 된다는 것에 어긋나기 때문이다.

===== 다중 인터페이스 구현 클래스

자바에서는 클래스를 다중 상속할 수 없다고 학습했다.

하지만 인터페이스는 다중 구현 클래스를 만들 수 있다.

[source, java]
----
public class ClassName implements InterfaceName1, InterfaceName2 {
  // InterfaceName1에 선언된 추상 메소드의 실체 메소드
  // InterfaceName2에 선언된 추상 메소드의 실체 메소드
}
----

==== 인터페이스 사용

인터페이스를 사용할 때는 인터페이스 변수를 선언하고 구현 객체를 대입해서 사용한다.

[source, java]
----
인터페이스 변수 = 구현객체;

or

인터페이스 변수;
변수 = 구현객체;
----

개발 코드에서 인터페이스는 클래스의 필드, 생성자 또는 메소드의 매개 변수, 생성자 또는 메소드의 로컬 변수로 선언될 수 있다.

===== 추상 메소드 사용

===== 디폴트 메소드 사용

===== 정적 메소드 사용

==== 타입 변환과 다형성

==== 인터페이스 상속

==== 디폴트 메소드와 인터페이스 확장
