= 11장. 기본 API 클래스

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon94@gmail.com
:Date: 2020.10.10
:Revision: 1.0
:imagesdir: ./image


책 '이것이 자바다 - 신용권'를 학습하면서 기억해두면 좋은점을 기록한다.

여러번 보면서 놓쳤던 부분들을 체크하며, 기본에 충실한다.

{Author}<{Email}>

---

==== 자바 API 도큐먼트

11장 부터는 자바에서 제공하는 API(Application Programming Interface)를 학습한다.

API는 라이브러리라고 부르기도 하는데, 프로그램 개발에 자주 사용되는 클래스 및 인터페이스의 모음을 말한다.

String 클래스와 System 클래스도 모두 API에 속하는 클래스들이다.

[TIP]
====
API 도큐먼트는 HTML 페이지로 작성되어 있기 때문에 웹 브라우저를 열고 오라클에서 제공하는 URL을 방문하면 볼 수 있다.

link:http://docs.oracle.com/javase/8/docs/api/[JAVA 8 API Document]

다른 버전의 API Document를 확인하고 싶다면
link:https://docs.oracle.com/en/java/javase/index.html[여기]에서 확인할 수 있다.

현재 Latest Release는 JDK 15 버전이다.
====

==== java.lang과 java.util 패키지

자바를 이용해 개발할 때 가장 만이 사용하는 패키지는 java.lang, java.util, java.time 패키지일 것이다.

* java.lang
** 자바 프로그램의 기본적인 클래스를 담고 있는 패키지
** import 없이 사용할 수 있음
** Object, System, Class, String, StringBuffer, StringBuilder, Math, Wrapper 등

* java.util
** 자바 프로그램 개발에 조미료 같은 역할을 하는 클래스를 포함
** 컬렉션 클래스들이 대부분을 차지(15장)
** Arrays, Calendar, Date, Objects, StringTokenizer, Random 등

==== Object 클래스

클래스를 선언할 때 extends 키워드로 다른 클래스를 상속하지 않으면 암시적으로 java.lang.Object 클래스를 상속하게 된다.

Object 클래스는 자바의 최상위 부모 클래스이다.

* equals()
** 비교 연산자인 ==과 동일한 결과를 리턴한다.
** equals() 메소드의 매개 타입은 Object로 모든 객체가 매개값으로 대입될 수 있다.
** 두 객체를 비교해서 논리적으로 동등하면 true, 논리적으로 동등하단 것은 같은 객체이건 다른 객체이건 상관없이 객체가 저장하고 있는 데이터가 동일함을 뜻한다.
** Object의 equals() 메소드는 직접 사용되지 않고 하위 클래스에서 재정의하여 사용된다.

[source, java]
----
public boolean equals(Object obj) { ... }

// 예시

Object obj1 = new Object();
Object obj2 = new Object();

// 결과 동일
boolean result = obj1.equals(obj2);
boolean result = (obj1 == obj2);
----

.equals() 메소드 재정의
[source, java]
----
public class Member {
  public String id;

  public Member(String id) {
    this.id = id;
  }

  @Override
  public boolean equals(Object obj) {
    if(obj instanceof Member) { // 매개값이 해당 클래스 타입인지 확인
      Member member = (Member) obj;
      if(id.equals(member.id)) {
        return true;
      }
    }
    return false;
  }
}
----


* hashCode()
* toString()
* clone()
* finalize()
