= 6장. 클래스

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon94@gmail.com
:Date: 2020.08.29
:Revision: 1.0
:imagesdir: ./image


책 '이것이 자바다 - 신용권'를 학습하면서 기억해두면 좋은점을 기록한다.

여러번 보면서 놓쳤던 부분들을 체크하며, 기본에 충실한다.

{Author}<{Email}>

---

==== 객체 지향 프로그래밍

객체 지향 프로그래밍은 Object Oriented Programming, OOP라고 한다.

객체란, 현실세계를 객체라는 물리적으로 존재하거나 추상적으로 생각할 수 있는 것 중에서 속성을 가지고 다른 것과 식별이 가능한 것을 말한다.

예를 들면, 컴퓨터는 모델명, 가격, 생산년도, 브랜드 등의 속성을 갖고 켜진다, 실행한다, 검색한다 등 동작을 갖는다.

자바에서는 이 속성과 동작을 필드(field)와 메소드(method)라고 부른다.

현실 세계에서는 객체와 객체간의 상호작용으로 삶을 살아간다.
예를들면 사람이 맥북을 사용하여 프로그래밍을 한다던지 넷플릭스를 본다던지 하는 행위 모두 사람과 맥북의 상호작용이다.

프로그램에서도 마찬가지다 각 객체는 독립적으로 존재하지만 다른 객체와의 상호작용으로 전체 프로그램이 동작한다.
이때 객체간의 상호작용을 하게해주는 것이 메소드 호출이다.

* 객체 지향 프로그래밍의 특징

** 캡슐화
*** 캡슐화란 실제 구현 내용에 접근제한자 등을 이용하여 내용을 감추는 것을 말한다.
*** 값이 변경되면 안되는 필드나 사용자가 몰라도 되는 중요한 부분은 캡슐화를 통해서 사용자에게는 감춘다.

** 상속
*** 상속은 현실세계와 비슷한 양상의 뜻으로 쓰인다. 부모 클래스가 가진 것을 상속받은 자식 클래스에서도 쓸 수 있다.
*** 상속은 미리 코딩해둔 클래스를 재사용하기 때문에 반복된 코드의 중복을 줄요준다.

** 다형성
*** 다형성은 하나의 타입에 여러 객체를 대입할 수 있다. 부모 클래스 타입, 인터페이스의 변수에 자식클래스, 구현 클래스의 타입 변환을 허용한다.

==== 객체와 클래스

현실에서 자동차를 생산한다고 생각하자.

자동차는 한대만 만드는 것이 아니고 고객 소요를 예측하여 많은 수량을 생산해야 한다.

자동차를 만들기 전 설계를 통해 자동차를 만드는 방법을 먼저 구상하지 않겠나. 클래스와 객체도 여기에 비교해 볼 수 있다.

자동차를 만들기 위한 설계를 하는 과정이 개발자가 클래스를 설계하는 과정이고,

공장에서 자동차를 만드는 과정은 클래스를 통해 객체를 생성하는 과정이다.

하나의 설계도가 있다면 같은 자동차를 생성하는 것은 가능하니 말이다.

---

클래스 선언은 class 키워드를 사용한다.

[source, java]
----
public class JangBong {

}
----

클래스 이름은 몇가지 작성 규칙이 있다.

** 클래스 이름 작성 규칙
*** 하나 이상의 문자로 이루어져야 한다.
*** 첫 번째 글자는 숫자가 올 수 없다.
*** '$','_' 외의 특수문자는 사용할 수 없다.
*** 자바 키워드는 사용할 수 없다.

[IMPORTANT]
====
자바는 파일 이름과 동일한 이름의 클래스에만 public 접근 제한자를 붙일 수 있다.
====

객체 생성은 new 키워드를 통해서 할 수 있다.

[source, java]
----
JangBong jang;
jang = new JangBong();

JangBong bong = new JangBong();
----

new 연산자로 객체를 생성하면 스택 영역에 변수가 생성되고 그 값은 생성된 객체의 주소를 값으로 가진다.

[TIP]
====
클래스 용도,

클래스는 두 가지 용도가 있다. 하나는 라이브러리(API: Application Program Interface)용이고 다른 하나는 실행용이다.

실행용 클래스는 main() 메소드를 통해 진입점을 제공한다.
====

==== 클래스의 구성 멤버

클래스에는 객체가 가져야할 구성 멤버를 선언한다. 크게 필드, 생성자, 메소드가 있다.

. 필드
.. 객체의 고유 데이터, 상태 등을 저장하는 공간

.. 선언 형태는 변수와 비슷하지만 변수라고 부르진 않는다.
... 변수는 생명주기가 생성자나 메소드의 중괄호 안에서만 사용된다.

. 생성자
.. new 연산자로 호출되는 중활호 블록이다.
.. 객체 생성 시 초기화를 담당한다.
.. 메소드와 생김새가 비슷하나 생성자는 이름이 클래스 이름으로 되어 있고 리턴타입이 없다.

. 메소드
.. 메소드는 객체에서 동작에 해당하는 블록이다.
.. 메소드는 객체 간의 데이터 전달의 수단으로 사용된다.

===== 필드

필드의 선언은 클래스 블록 내에서는 어디에나 존재할 수 있다. 예전에 C언어를 공부할때는 변수 선언은 무조건 상단부에 했어야 했는데 자바는 어디서든 상관없다.

[source, java]
----
타입 필드이름 [ = 초기값];

String name = "장봉";
int age = 27;
----

필드의 사용은 생성자나 메소드에서 사용한다. 외부에서 필드를 사용하려면 우선 객체를 생성해야한다.

객체가 존재하지 않으면 필드도 존재하지 않는다.

[source, java]
----
public class Jang {
  int age = 27;
  String name = "장봉";
  String address = "서울";
}
//----------------------------------------
public class JangExample {
  public static void main(String[] args) {
    Jang jang = new Jang();

    System.out.println("이름 : " + jang.name);
    System.out.println("나이 : " + jang.age);
    System.out.println("주소 : " + jang.address);

  }
}
----

===== 생성자

모든 클래스에는 생성자가 반드시 존재한다. 따로 코딩하지 않아도 기본 생성자를 컴파일러가 바이트 코드에 추가한다.

생성자는 매개 변수를 생략할 수도 있고, 여러 개를 선언할 수 있다.

[source, java]
----
Jang jang = new Jang("장봉", 27, "서울");
----

위와 같이 객체를 생성하고 싶다면 다음과 같이 매개 변수가 존재하는 생성자를 사용하면 된다.

[source, java]
----
public class Jang {
  int age;
  String name;
  String address;

  Jang(String name, int age, String address) {
    this.name = name;
    this.age = age;
    this.address = address;
  }
}
----

관례적으로 매개 변수와 필드 이름을 동일하게 선언하고 필드는 this 키워드를 사용해 구분해준다.

this는 객체 자기 자신을 참조하는 것으로 사용된다.

그런데 만약 객체를 생성할 때, 이름과 나이는 입력하는데 주소는 입력하고싶지 않을수도 있다.

이럴 경우엔 생성자 *오버로딩* 을 통해 매개 변수 값을 다르게 생성자를 여러 개 선언하면 된다.

[source, java]
----
public class Jang {
  int age;
  String name;
  String address;

  Jang() {}

  Jang(String name) {
    this(name, 20, "서울");
  }

  Jang(String name, int age) {
    this(name, age, "서울");
  }

  Jang(String name, int age, String address) {
    this.name = name;
    this.age = age;
    this.address = address;
  }
}
----

this를 사용하면 코드의 중복을 줄일 수 있다.

===== 메소드

메소드는 리턴타입, 메소드이름, 매개변수 선언과 실행부로 구성된다.

리턴타입은 메소드가 실행된 후 리턴하는 값의 타입이다. 리턴값은 있어도되고 없어도 된다.

리턴타입이 있다면 메소드를 호출할 때 리턴값을 저장할 변수를 선언한 후 리턴값을 저장하는데 리턴값이 있다고 무조건 변수가 필요한건 아니다.

메소드 이름은 자바 식별자 규칙에 맞게 작성하면 된다.

개발자들의 작은 규칙으로는 메소드 이름 시작은 영어 소문자로하고 두개 이상의 단어가 이름으로 쓰인다면 뒤이어 오는 단어의 첫글자는 대문자로 한다. 이를 Camel표기법이라고 부른다.

[source, java]
----
class Person {
  String name;
  int age;
  String address;

  void namePrint() {
    System.out.println("이름은 장봉입니다.");
  }

  String getName() {
    return this.name;
  }

  void changeName(String newName) {
    this.name = newName;
  }
}
----

매개 변수의 갯수를 모를경우엔 배열을 이용해 매개변수를 선언할 수 있다.

[source, java]
----
int sum(int[] values) {}

int[] values = {1,2,3}
int result = sum(values);
int result = sum(new int[] {1,2,3,4,5});
----

====
매개 변수를 배열 타입으로 선언하면 메소드 호출하기 전에 배열을 생성해야하는 수고스러움이 있다.

이 문제를 해결하기 위한 방법은 다음과 같다.

[source, java]
----
int sum2(int ... values) {}

int result = sum2(1,2,3);
int result = sum2(1,2,3,4,5);
----

"..."로 선언된 매개 변수의 값은 위와 같이 메소드 호출 시 리스트로 나열해주면 된다.
====

메소드는 클래스 내,외부의 호출에 의해 실행된다.

내부에서 호출할경우 메소드 이름만으로 호출이 가능하지만 외부 클래스에서 호출할 경우엔 우선 해당 클래스의 객체를 생성한 뒤 호출해야한다.

[source, java]
----
class Person {
  String name;
  int age;

  Person(String name) {
    this.name = name;
  }

  String getName() {
    return this.name;
  }
}

public class PersonExample {
  public static void main(String[] args) {
    Person person = new Person("장봉");

    System.out.println("이름은 " + person.getName() + "입니다.");
  }
}
----

자바는 매개 변수 타입을 우선적으로 확인하지만 타입이 불일치할 경우엔 자동 타입변환이 가능한지 검사한다.

===== 인스턴스 멤버와 this

인스턴스 멤버란 객체를 생성한 후 사용할 수 있는 필드와 메소드를 말한다.

인스턴스 필드와 메소드는 객체에 소속된 멤버이기 때문에 객체 없이는 사용할 수 없다.

객체가 생성된 후 메모리 영역을 살펴보면 메소드는 각 객체마다 존재하지않고 메소드 영역에 저장되어 공유된다.

this는 메소드에도 사용이 가능하다. 자기 자신을 가르키는 것으로 자신이 가지고 있는 필드나 객체를 선택할 수 있다.

===== 정적 멤버와 static

정적 멤버는 객체에 소속되지 않고 클래스에 소소된 멤버이다.(클래스 멤버라고도 표현)

각 객체마다 특성으로 쓰이지 않고 공통적으로 사용되는 데이터는 static으로 선언하는 것이 좋다.

[source, java]
----
public class Calculator {
  String model;
  static double pi = 3.14159;
  static int plus(int x, int y) {
    return x + y;
  }
}
----

정적 필드와 정적 메소드는 원칙상 클래스 이름으로 호출하는 것이 맞지만 객체 참조변수로도 접근이 가능하다.

정적 필드는 다음과 같이 선언시 블록을 이용할 수 있다.

[source,java]
----
static {
  name = firstName + " " + lastName;
}
----

[TIP]
====
정적 메소드와 정적 블록 선언 시 주의할점,

객체가 없이 사용될 수 있는 클래스 멤버로서 this 키워드를 사용할 수 없다.
====

===== 싱글톤(Singleton)

디자인패턴 중 하나로 프로그램 실행도중에 객체를 단 하나만 만들도록 보장해주는 방법이다.

책에서 나온 가장 간단한 방법으로는 생성자를 private로 지정해줘서 외부에서 객체를 생성하지 못하도록 하는것이다.

[source, java]
----
public class Singleton{
  private static Singleton singleton = new Singleton();


  private Singleton() {}

    static Singleton getInstance() {
      return singleton;
    }
}
----

자세한 사항은 link:https://github.com/ByeongSoon/TIL/blob/master/DesignPattern/SingletonPattern.adoc[여기]를 참고하길 바란다

===== final 필드와 상수

final 키워드의 의미는 최종적이라는 뜻을 가지고 있다.

final 키워드를 사용한 필드에 값이 저장되면 해당 필드는 값을 변경할 수 없다.

[TIP]
====
final 필드의 초기값을 설정하는 방법

. 필드를 선언하면서 값을 준다.
. 생성자를 통해서 값을 준다.

만일 final 필드를 생성자를 통해서도 값을 저장하지 않으면 컴파일 오류가 발생한다.
====

상수란 불변의 값을 뜻한다. 우리가 변수는 변동 가능한 값을 의미하는것처럼 말이다.

불변의 값은 수학에서 사용하는 원주율 등이 해당될 수 있다.

final 키워드만을 가지고는 상수라고 말할 수 없다. 각 객체마다 생성되기에 다른 값으로 초기화가 가능하기 때문이다.

그래서 우리는 final과 static을 함께 사용하여 클래스 멤버로서 값을 변경할 수 없는 상수를 선언한다.

[source, java]
----
static final double PI = 3.14159;
----

===== 패키지

자바에서는 클래스를 효율적으로 관리하기 위해 패키지를 사용한다.

패키지는 우리가 컴퓨터를 사용할 때 폴던를 만들어 문서를 정리하는 것처럼 패키지를 만들어 클래스를 정리하여 관리한다.

다른 패키지에 있는 클래스를 사용할 경우엔 import문을 사용한다.

import문은 패키지 선언과 클래스 선언 사이에 위치한다.

[TIP]
====
서로 다른 패키지를 import 해왔는데 두 패키지에 같은 이름의 클래스가 존재한다고하면 클래스 사용시에 패키지 이름까지 모두 적어줘야한다.

그렇지 않으면 컴파일러는 어떤 클래스를 사용해야할지 몰라서 컴파일 에러가 발생한다.
====

===== 접근제한자

대부분의 클래스는 외부에서 사용할 목적으로 만든다. 이때 클래스 멤버에 접근 제한자를 이용해 특정 데이터를 보호해야한다.

접근 제한자는 public, protected, default, private 네 종류가 있다.

protected 접근 제한자는 같은 패키지 또는 자식 클래스에서 사용할 수 있다.

클래스에 적용 가능한 접근 제한자는 public, default 두 가지이다.

클래스를 다른 개발자가 사용할 수 있도록 라이브러리로 만들 경우엔 public 접근 제한자를 가져야 한다.

생성자를 따로 선언하지 않고 자동으로 생성된다면 생성자의 접근 제한자는 클래스의 접근 제한자를 따른다. 생성자가 어떤 접근 제한을 갖느냐에 따라서 호출 가능 여부가 결정된다.

private로 생성자를 선언한다면 클래스 외부에서 new 연산자로 객체를 만들수 없다. 이 부분은 싱글톤패턴에서 잠시 보았던 내용이다.

===== Getter & Setter

일반적으로 객체의 데이터는 외부에서 접근하는 것을 막는다. 외부에서 마음대로 변경할 경우에 객체의 무결성이 깨진다.

이러한 문제로 객체 지향 프로그래밍에서는 메소드를 통해서 필드의 값을 변경하는 것을 선호하는데 이런 역할을 하는 것이 Setter이다.

Setter를 이용하면 데이터의 값을 변경하기전에 변경하려는 데이터를 검증한 뒤에 변경할 수 있다.

[source, java]
----
void setAge(int age) {
  if(age < 0) {
    this.age = 0;
    return;
  }else {
    this.age = age;
  }
}
----

클래스를 선언할 때 가능하면 필드는 private로 선언하고 메소드를 통해서 필드에 대한 Getter, Setter 메소드를 작성해서 안전하게 사용/변경하는 것이 좋다.

Getter, Setter은 사용하는 IDE에서 자동으로 생성할 수 있다.

[TIP]
====
IntelliJ에서 Getter, Setter 자동생성 방법,

추후 정리
====

===== 어노테이션

어노테이션은 컴파일 과정과 싱행 과정에서 코드를 어떻게 컴파일하고 처리할 것인지를 알려준다.

* 어노테이션 사용 용도
. 컴파일러에게 코드 문법 에러 체크하도록 정보 제공
. 개발 툴이 빌드나 배치 시 코드를 자동으로 생성하도록 정보 제공
. 실행(런타임) 시 특정 기능을 실행하도록 정보 제공

대표적인 어노테이션으로는 @Override가 있다. 상속받은 메소드를 재정의한 것을 컴파일러가 알 수 있게 표현해 준다.

어노테이션은 빌드 시 자동적으로 XML파일이나 JAR파일을 생성하는데에도 사용된다.

어노테이션의 선언은 @interface를 사용한다.

[source,java]
----
public @interface AnnotationName {
  Type elementName1() [default value];
  Type elementName2() [default value];
  ...
}

@AnnotationName(elementName1="값", elementName2="값")

// elementName을 사용하지 않고 기본 엘리먼트인 value를 가질 수 있다.
public @interface AnnotationName {
  Type value();
  int elementName() default 5;
}

@AnnotationName(value="값", elementName=3)
----

[IMPORTANT]
====
어노테이션 적용 대상,

클래스, 필드, 메소드만 어노테이션을 적용할 수 있고 생성자에는 적용할 수 없다.

[source,java]
----
@AnnotationName
public class ClassName {
  @AnnotationName
  private String field;

  //@AnnotationName (x)
  public ClassName() { }

  @AnnotationName
  public void setField(int field) {
    this.field = field;
  }
}
----
====
