= 11장. 기본 API 클래스

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon94@gmail.com
:Date: 2020.10.10
:Revision: 1.0
:imagesdir: ./image


책 '이것이 자바다 - 신용권'를 학습하면서 기억해두면 좋은점을 기록한다.

여러번 보면서 놓쳤던 부분들을 체크하며, 기본에 충실한다.

{Author}<{Email}>

---

==== 자바 API 도큐먼트

11장부터는 자바에서 제공하는 API(Application Programming Interface)를 학습한다.

API는 라이브러리라고 부르기도 하는데, 프로그램 개발에 자주 사용되는 클래스 및 인터페이스의 모음을 말한다.

String 클래스와 System 클래스도 모두 API에 속하는 클래스들이다.

[TIP]
====
API 도큐먼트는 HTML 페이지로 작성되어 있기 때문에 웹 브라우저를 열고 오라클에서 제공하는 URL을 방문하면 볼 수 있다.

link:http://docs.oracle.com/javase/8/docs/api/[JAVA 8 API Document]

다른 버전의 API Document를 확인하고 싶다면
link:https://docs.oracle.com/en/java/javase/index.html[여기]에서 확인할 수 있다.

현재 Latest Release는 JDK 15 버전이다.('20.10.10 기준)
====

==== java.lang과 java.util 패키지

자바를 이용해 개발할 때 가장 만이 사용하는 패키지는 java.lang, java.util, java.time 패키지일 것이다.

* java.lang
** 자바 프로그램의 기본적인 클래스를 담고 있는 패키지
** import 없이 사용할 수 있음
** Object, System, Class, String, StringBuffer, StringBuilder, Math, Wrapper 등

* java.util
** 자바 프로그램 개발에 조미료 같은 역할을 하는 클래스를 포함
** 컬렉션 클래스들이 대부분을 차지(15장에서 학습)
** Arrays, Calendar, Date, Objects, StringTokenizer, Random 등

==== Object 클래스

클래스를 선언할 때 extends 키워드로 다른 클래스를 상속하지 않으면 암시적으로 java.lang.Object 클래스를 상속하게 된다.

Object 클래스는 자바의 최상위 부모 클래스이다.

* equals()
** 비교 연산자인 ==과 동일한 결과를 리턴한다.
** equals() 메소드의 매개 타입은 Object로 모든 객체가 매개값으로 대입될 수 있다.
** 두 객체를 비교해서 논리적으로 동등하면 true, 논리적으로 동등하단 것은 같은 객체이건 다른 객체이건 상관없이 객체가 저장하고 있는 데이터가 동일함을 뜻한다.
** Object의 equals() 메소드는 직접 사용되지 않고 하위 클래스에서 재정의하여 사용된다.

[source, java]
----
public boolean equals(Object obj) { ... }

// 예시

Object obj1 = new Object();
Object obj2 = new Object();

// 결과 동일
boolean result = obj1.equals(obj2);
boolean result = (obj1 == obj2);
----

.equals() 메소드 재정의
[source, java]
----
public class Member {
  public String id;

  public Member(String id) {
    this.id = id;
  }

  @Override
  public boolean equals(Object obj) {
    if(obj instanceof Member) { // 매개값이 해당 클래스 타입인지 확인
      Member member = (Member) obj;
      if(id.equals(member.id)) {
        return true;
      }
    }
    return false;
  }
}
----

* hashCode()
** 객체 해시코드란 객체를 식별할 하나의 정수값이다.
** hashCode() 메소드는 객체의 메모리 번지를 이용해 해시코드를 만들어 리턴하기 때문에 객체마다 다른 값을 가지고 있다.
** 컬렉션 프레임워크에서 HashSet, HashMap, HashTable은 hashCode() 메소드를 실행해서 리턴된 해시코드 값이 같은지를 비교하고, 같다면 equals() 메소드로 다시 비교한다.
** hashCode() 메소드는 재정의를 통해서 많이 사용한다.

.hashCode() 재정의하지 않음
[source, java]
----
public class Key {
  public int number;

  public Key(int number) {
    this.number = number;
  }

  @Override
  public boolean equals(Object obj) {
    if(obj instanceof Key) {
      Key compareKey = (Key) obj;
      if(this.number == compareKey.number) {
        return true;
      }
    }
    return false;
  }
}

// hashCode() 메소드 재정의 하지 않으면 다른 키로 인식
public class KeyExample {
  public static void main(String[] args) {
    HashMap<Key, String> hashMap = new HashMap<Key, String>();

    hashMap.put(new Key(1), "장봉");

    String value = hashMap.get(new Key(1));
    System.out.println(value); // null 값이 출력
  }
}
----

.hashCode() 메소드 재정의
[source, java]
----
public class Key {
  ...

  @Override
  public int hashCode() {
    return number;
  }

  ...
}
----

* toString()
** 객체의 문자 정보를 리턴한다.
** Object 클래스의 toString() 메소드는 "클래스명@16진수 해시코드"로 구성된 문자 정보 리턴
** Object의 toString() 메소드의 리턴값은 별 의미가 없으므로 메소드를 재정의하여 유용한 정보를 리턴하도록 한다.
** 예를들어 java.util의 Date 클래스는 toString() 메소드로 현재 시스템의 날짜와 시간 정보를 리턴한다.
** 예 : SmartPhone 클래스에서 toString() 메소드를 오버라이딩하여 제작사와 운영체제를 리턴

.toString() 예제
[source, java]
----
public class ToStringExample {
  public static void main(String[] args) {
    Object obj1 = new Object();
    Date obj2 = new Date();

    System.out.println(obj1.toString());
    System.out.println(obj2.toString());
  }
}
----

----
java.lang.Object@11bbd2
SUN OCT 11 21:00:05 KST 2020
----

* clone()
** 객체 복제는 원본 객체의 필드값과 동일한 값을 가지는 새로운 객체를 생성하는 것을 뜻한다.
** 객체 복제 이유는 원본 객체를 보호하기 위함
** 객체 복제 방법에는 얕은 복제와 깊은 복제가 있다.
** 얕은 복제(thin clone) : 단순히 필드값을 복사해서 객체를 복제하는 것
** 깊은 복제(deep clone) : 참조하고 있는 객체도 복제하는 것

(복제 관련 내용 추가해야함)

* finalize()
** 참조하지 않는 배열이나 객체는 Garbage Collector가 힙 영역에서 자동적으로 소멸시킨다.
** finalize()는 Garbage Collector가 객체를 소멸하기 직전에 실행시킨다.
** Object의 finalize()는 기본적으로 실행내용이 없으나, 객체 소멸전에 자원을 닫거나 중요한 데이터를 저장하고자 한다면 재정의를 통해서 할 수 있다.

(finalize() 관련 예제 추가해야함)

==== Objects 클래스

Object와 유사한 이름을 가진 java.util.Objects 클래스는 객체비교, 해시코드 생성, null 여부, 객체 문자열 리턴 등의 연산을 수행하는 정적 메소드들로 구성된 클래스이다.

* 객체 비교(compare(T a, T b, Comparator<T>c))
* 동등 비교(equals()와 deepEquals())
* 해시코드 생성(hash(), hashCode())
* 널 여부(isNull(), nonNull(), requireNonNull())
* 객체 문자 정보(toString())

==== System 클래스

자바 프로그램은 JVM(Java Virtual Machine) 위에서 실행된다. 운영체제의 모든 기능을 자바 코드로 접근하기는 어렵다.

java.lang.System 클래스를 이용하면 운영체제의 기능중 일부를 이용할 수 있다.

예를 들어 프로그램 종료, 키보드 입력, 모니터 출력, 메모리 정리, 현재 시간 읽기, 시스템 프로퍼티 읽기, 환경 변수 읽기 등이 가능하다.

System 클래스의 모든 필드와 메소드는 정적(static) 필드와 정적(static) 메소드로 구성되어 있다.

==== Class 클래스

클래스와 인터체이스의 메타 데이터를 java.lang.Class 클래스로 관리한다.
(메타 데이터란 클래스의 이름, 생성자 정보, 필드 정보, 메소드 정보 등)

* getClass(), forName()
* getDeclaredConstructors(), getDeclaredFields(), getDeclaredMethods()
* newInstance()


==== String 클래스

프로그램을 작성할때 문자열이 많이 사용된다. 문자열을 생성, 추출, 비교, 분리, 변환 등을 제공하는 메소드에 대해서 알아본다.

====== String 생성자

====== String 메소드

* charAt()
* equals()
* getBytes()
* indexOf()
* length()
* replace()
* substring()
* toLowerCase(), toUpperCase()
* trim()
* valueOf()
