= 6장. 클래스

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon94@gmail.com
:Date: 2020.08.26
:Revision: 1.0
:imagesdir: ./image


책 '이것이 자바다 - 신용권'를 학습하면서 기억해두면 좋은점을 기록한다.

여러번 보면서 놓쳤던 부분들을 체크하며, 기본에 충실한다.

Byeongsoon Jang<byeongsoon94@gmail.com>

---

==== 객체 지향 프로그래밍

객체 지향 프로그래밍은 Object Oriented Programming, OOP라고 한다.

객체란, 현실세계를 객체라는 물리적으로 존재하거나 추상적으로 생각할 수 있는 것 중에서 속성을 가지고 다른 것과 식별이 가능한 것을 말한다.

예를 들면, 컴퓨터는 모델명, 가격, 생산년도, 브랜드 등의 속성을 갖고 켜진다, 실행한다, 검색한다 등 동작을 갖는다.

자바에서는 이 속성과 동작을 필드(field)와 메소드(method)라고 부른다.

현실 세계에서는 객체와 객체간의 상호작용으로 삶을 살아간다.
예를들면 사람이 맥북을 사용하여 프로그래밍을 한다던지 넷플릭스를 본다던지 하는 행위 모두 사람과 맥북의 상호작용이다.

프로그램에서도 마찬가지다 각 객체는 독립적으로 존재하지만 다른 객체와의 상호작용으로 전체 프로그램이 동작한다.
이때 객체간의 상호작용을 하게해주는 것이 메소드 호출이다.

* 객체 지향 프로그래밍의 특징

** 캡슐화
*** 캡슐화란 실제 구현 내용에 접근제한자 등을 이용하여 내용을 감추는 것을 말한다.
*** 값이 변경되면 안되는 필드나 사용자가 몰라도 되는 중요한 부분은 캡슐화를 통해서 사용자에게는 감춘다.

** 상속
*** 상속은 현실세계와 비슷한 양상의 뜻으로 쓰인다. 부모 클래스가 가진 것을 상속받은 자식 클래스에서도 쓸 수 있다.
*** 상속은 미리 코딩해둔 클래스를 재사용하기 때문에 반복된 코드의 중복을 줄요준다.

** 다형성
*** 다형성은 하나의 타입에 여러 객체를 대입할 수 있다. 부모 클래스 타입, 인터페이스의 변수에 자식클래스, 구현 클래스의 타입 변환을 허용한다.

==== 객체와 클래스

현실에서 자동차를 생산한다고 생각하자.

자동차는 한대만 만드는 것이 아니고 고객 소요를 예측하여 많은 수량을 생산해야 한다.

자동차를 만들기 전 설계를 통해 자동차를 만드는 방법을 먼저 구상하지 않겠나. 클래스와 객체도 여기에 비교해 볼 수 있다.

자동차를 만들기 위한 설계를 하는 과정이 개발자가 클래스를 설계하는 과정이고,

공장에서 자동차를 만드는 과정은 클래스를 통해 객체를 생성하는 과정이다.

하나의 설계도가 있다면 같은 자동차를 생성하는 것은 가능하니 말이다.

---

클래스 선언은 class 키워드를 사용한다.

[source, java]
----
public class JangBong {

}
----

클래스 이름은 몇가지 작성 규칙이 있다.

** 클래스 이름 작성 규칙
*** 하나 이상의 문자로 이루어져야 한다.
*** 첫 번째 글자는 숫자가 올 수 없다.
*** '$','_' 외의 특수문자는 사용할 수 없다.
*** 자바 키워드는 사용할 수 없다.

[IMPORTANT]
====
자바는 파일 이름과 동일한 이름의 클래스에만 public 접근 제한자를 붙일 수 있다.
====

객체 생성은 new 키워드를 통해서 할 수 있다.

[source, java]
----
JangBong jang;
jang = new JangBong();

JangBong bong = new JangBong();
----

new 연산자로 객체를 생성하면 스택 영역에 변수가 생성되고 그 값은 생성된 객체의 주소를 값으로 가진다.

[TIP]
====
클래스 용도,

클래스는 두 가지 용도가 있다. 하나는 라이브러리(API: Application Program Interface)용이고 다른 하나는 실행용이다.

실행용 클래스는 main() 메소드를 통해 진입점을 제공한다.
====

==== 클래스의 구성 멤버
