= 6장. 클래스

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon94@gmail.com
:Date: 2020.08.27
:Revision: 1.0
:imagesdir: ./image


책 '이것이 자바다 - 신용권'를 학습하면서 기억해두면 좋은점을 기록한다.

여러번 보면서 놓쳤던 부분들을 체크하며, 기본에 충실한다.

Byeongsoon Jang<byeongsoon94@gmail.com>

---

==== 객체 지향 프로그래밍

객체 지향 프로그래밍은 Object Oriented Programming, OOP라고 한다.

객체란, 현실세계를 객체라는 물리적으로 존재하거나 추상적으로 생각할 수 있는 것 중에서 속성을 가지고 다른 것과 식별이 가능한 것을 말한다.

예를 들면, 컴퓨터는 모델명, 가격, 생산년도, 브랜드 등의 속성을 갖고 켜진다, 실행한다, 검색한다 등 동작을 갖는다.

자바에서는 이 속성과 동작을 필드(field)와 메소드(method)라고 부른다.

현실 세계에서는 객체와 객체간의 상호작용으로 삶을 살아간다.
예를들면 사람이 맥북을 사용하여 프로그래밍을 한다던지 넷플릭스를 본다던지 하는 행위 모두 사람과 맥북의 상호작용이다.

프로그램에서도 마찬가지다 각 객체는 독립적으로 존재하지만 다른 객체와의 상호작용으로 전체 프로그램이 동작한다.
이때 객체간의 상호작용을 하게해주는 것이 메소드 호출이다.

* 객체 지향 프로그래밍의 특징

** 캡슐화
*** 캡슐화란 실제 구현 내용에 접근제한자 등을 이용하여 내용을 감추는 것을 말한다.
*** 값이 변경되면 안되는 필드나 사용자가 몰라도 되는 중요한 부분은 캡슐화를 통해서 사용자에게는 감춘다.

** 상속
*** 상속은 현실세계와 비슷한 양상의 뜻으로 쓰인다. 부모 클래스가 가진 것을 상속받은 자식 클래스에서도 쓸 수 있다.
*** 상속은 미리 코딩해둔 클래스를 재사용하기 때문에 반복된 코드의 중복을 줄요준다.

** 다형성
*** 다형성은 하나의 타입에 여러 객체를 대입할 수 있다. 부모 클래스 타입, 인터페이스의 변수에 자식클래스, 구현 클래스의 타입 변환을 허용한다.

==== 객체와 클래스

현실에서 자동차를 생산한다고 생각하자.

자동차는 한대만 만드는 것이 아니고 고객 소요를 예측하여 많은 수량을 생산해야 한다.

자동차를 만들기 전 설계를 통해 자동차를 만드는 방법을 먼저 구상하지 않겠나. 클래스와 객체도 여기에 비교해 볼 수 있다.

자동차를 만들기 위한 설계를 하는 과정이 개발자가 클래스를 설계하는 과정이고,

공장에서 자동차를 만드는 과정은 클래스를 통해 객체를 생성하는 과정이다.

하나의 설계도가 있다면 같은 자동차를 생성하는 것은 가능하니 말이다.

---

클래스 선언은 class 키워드를 사용한다.

[source, java]
----
public class JangBong {

}
----

클래스 이름은 몇가지 작성 규칙이 있다.

** 클래스 이름 작성 규칙
*** 하나 이상의 문자로 이루어져야 한다.
*** 첫 번째 글자는 숫자가 올 수 없다.
*** '$','_' 외의 특수문자는 사용할 수 없다.
*** 자바 키워드는 사용할 수 없다.

[IMPORTANT]
====
자바는 파일 이름과 동일한 이름의 클래스에만 public 접근 제한자를 붙일 수 있다.
====

객체 생성은 new 키워드를 통해서 할 수 있다.

[source, java]
----
JangBong jang;
jang = new JangBong();

JangBong bong = new JangBong();
----

new 연산자로 객체를 생성하면 스택 영역에 변수가 생성되고 그 값은 생성된 객체의 주소를 값으로 가진다.

[TIP]
====
클래스 용도,

클래스는 두 가지 용도가 있다. 하나는 라이브러리(API: Application Program Interface)용이고 다른 하나는 실행용이다.

실행용 클래스는 main() 메소드를 통해 진입점을 제공한다.
====

==== 클래스의 구성 멤버

클래스에는 객체가 가져야할 구성 멤버를 선언한다. 크게 필드, 생성자, 메소드가 있다.

. 필드
.. 객체의 고유 데이터, 상태 등을 저장하는 공간

.. 선언 형태는 변수와 비슷하지만 변수라고 부르진 않는다.
... 변수는 생명주기가 생성자나 메소드의 중괄호 안에서만 사용된다.

필드의 선언은 클래스 블록 내에서는 어디에나 존재할 수 있다. 예전에 C언어를 공부할때는 변수 선언은 무조건 상단부에 했어야 했는데 자바는 어디서든 상관없다.

[source, java]
----
타입 필드이름 [ = 초기값];

String name = "장봉";
int age = 27;
----

필드의 사용은 생성자나 메소드에서 사용한다. 외부에서 필드를 사용하려면 우선 객체를 생성해야한다.

객체가 존재하지 않으면 필드도 존재하지 않는다.

[source, java]
----
public class Jang {
  int age = 27;
  String name = "장봉";
  String address = "서울";
}
//----------------------------------------
public class JangExample {
  public static void main(String[] args) {
    Jang jang = new Jang();

    System.out.println("이름 : " + jang.name);
    System.out.println("나이 : " + jang.age);
    System.out.println("주소 : " + jang.address);

  }
}
----

. 생성자
.. new 연산자로 호출되는 중활호 블록이다.
.. 객체 생성 시 초기화를 담당한다.
.. 메소드와 생김새가 비슷하나 생성자는 이름이 클래스 이름으로 되어 있고 리턴타입이 없다.

모든 클래스에는 생성자가 반드시 존재한다. 따로 코딩하지 않아도 기본 생성자를 컴파일러가 바이트 코드에 추가한다.

생성자는 매개 변수를 생략할 수도 있고, 여러 개를 선언할 수 있다.

[source, java]
----
Jang jang = new Jang("장봉", 27, "서울");
----

위와 같이 객체를 생성하고 싶다면 다음과 같이 매개 변수가 존재하는 생성자를 사용하면 된다.

[source, java]
----
public class Jang {
  int age;
  String name;
  String address;

  Jang(String name, int age, String address) {
    this.name = name;
    this.age = age;
    this.address = address;
  }
}
----

관례적으로 매개 변수와 필드 이름을 동일하게 선언하고 필드는 this 키워드를 사용해 구분해준다.

this는 객체 자기 자신을 참조하는 것으로 사용된다.

그런데 만약 객체를 생성할 때, 이름과 나이는 입력하는데 주소는 입력하고싶지 않을수도 있다.

이럴 경우엔 생성자 *오버로딩* 을 통해 매개 변수 값을 다르게 생성자를 여러 개 선언하면 된다.

[source, java]
----
public class Jang {
  int age;
  String name;
  String address;

  Jang() {}

  Jang(String name) {
    this(name, 20, "서울");
  }

  Jang(String name, int age) {
    this(name, age, "서울");
  }

  Jang(String name, int age, String address) {
    this.name = name;
    this.age = age;
    this.address = address;
  }
}
----

this를 사용하면 코드의 중복을 줄일 수 있다.

. 메소드
.. 메소드는 객체에서 동작에 해당하는 블록이다.
.. 메소드는 객체 간의 데이터 전달의 수단으로 사용된다.
